<div class="bjui-pageHeader">
    <form  id="pagerForm" method="get" action="<?php echo \Sooh\Base\Tools::uri(); ?>" data-toggle="ajaxsearch">
<!--        <input type="hidden" name="__formguid__" value="default" />-->
<!--        <input type="hidden" name="pageSize" value="--><?php //echo $this->pagesize; ?><!--">-->
<!--        <input type="hidden" name="pageCurrent" value="--><?php //echo $this->pageid; ?><!--">-->
<!--        <input type="hidden" name="orderField" value="${param.orderField}">-->
<!--        <input type="hidden" name="orderDirection" value="${param.orderDirection}">-->
        <label>时间从：</label>
        <input type="text" data-toggle="datepicker" name="ymdFrom" value="<?php echo $this->ymdFrom; ?>" size="18" />
        <label>时间到：</label>
        <input type="text" data-toggle="datepicker" name="ymdTo" value="<?php echo $this->ymdTo; ?>" size="18" />
        <label>渠道选择：</label>
        <select name='select' value="channel" id="ids" >
  
         <?php 
          $channel= $this->rem;
          $channels=$this->channels;
//var_log($channel,'66666>>>>>>>');
//var_log($channels,'chanel##########>>>>>>>');

           foreach ($channel as $k=>$v){
               
          ?>
             <option value="<?php echo $v;?>" <?php if($v==$channels) {echo "selected=\"selected\"";}?>><?php echo $v;?></option>
        <?php }?>
        </select>
           <input type="hidden" name="__VIEW__" value="<?php echo $this->_view;?>" size="18" />
       <button type="submit" class="btn btn-default">查询</button>
        &nbsp;
        <label style="color:red;"><?php echo $this->errMsg;?></label>
    </form> 
  </div>
     
<div class="bjui-pageContent">
   
     
   
   <!--<div id="newfinancial" style="height:330px"></div>-->
    
    <div id="newfinancial" style="height: 400px " width="100%"></div>
     <div id="newfinancial1" style="height: 400px " width="100%"></div>


     <style type="text/css">

     </style>
    <script type="text/javascript">

        require.config({
            paths:{
                echarts: '/echarts/dist'
        }
        });

        require(
            [
                'echarts',
                'echarts/chart/bar', // 使用柱状图就加载bar模块，按需加载
                //'echarts/chart/line', // 使用折线图就加载line模块，按需加载
                //'echarts/chart/stack', // 使用柱状图就加载bar模块，按需加载
                //'echarts/chart/tiled', // 使用柱状图就加载bar模块，按需加载
            ],
            function (ec) {

             
                // 基于准备好的dom，初始化echarts图表
                var myChart = ec.init(document.getElementById('newfinancial'));
                
                var records = <?=$this->records?>;
               
                var dtime = <?=$this->dtime?>;
                var dtime2 = {text:"<?=$this->dtime2;?>"};
                for(var tx in dtime2){
                   dtime22=dtime2[tx];
                }
                //console.log(dtime22);
           
                var t1='当天注册';
                var t2='前1天至前5天注册';
                var t3='前6天至前30天注册';
                var t4='前31天及更久注册';

                if(records==null){
                	tt1=dtime+t1; tt2=dtime+t2;
                    tt3=dtime+t3; tt4=dtime+t4;

                    fbb_countReg0Day=0;
                    fbb_countReg1To5=0;
                    fbb_countReg6To30=0;
                    fbb_countReg31Plus=0;

                    dqb_countReg0Day=0;
                    dqb_countReg1To5=0;
                    dqb_countReg6To30=0;
                    dqb_countReg31Plus=0;

                    jyb_countReg0Day=0;
                    jyb_countReg1To5=0;
                    jyb_countReg6To30=0;
                    jyb_countReg31Plus=0;
                    
                    }
                else{
                 for(var dt in records){
                    tt1=dt+t1; tt2=dt+t2;
                    tt3=dt+t3; tt4=dt+t4;
                   //fbb_countReg0Day=(parseInt(records[dt][fbb].countReg0Day);
                    
                   fbb_countReg0Day=parseInt(records[dt].fbb.countReg0Day);
                   fbb_countReg1To5=parseInt(records[dt].fbb.countReg1To5);
                   fbb_countReg6To30=parseInt(records[dt].fbb.countReg6To30);
                   fbb_countReg31Plus=parseInt(records[dt].fbb.countReg31Plus);

                   dqb_countReg0Day=parseInt(records[dt].dqb.countReg0Day);
                   dqb_countReg1To5=parseInt(records[dt].dqb.countReg1To5);
                   dqb_countReg6To30=parseInt(records[dt].dqb.countReg6To30);
                   dqb_countReg31Plus=parseInt(records[dt].dqb.countReg31Plus);

                   jyb_countReg0Day=parseInt(records[dt].jyb.countReg0Day);
                   jyb_countReg1To5=parseInt(records[dt].jyb.countReg1To5);
                   jyb_countReg6To30=parseInt(records[dt].jyb.countReg6To30);
                   jyb_countReg31Plus=parseInt(records[dt].jyb.countReg31Plus);

                  // console.log(dbq_countReg1To5);
                    }
                    }


                // 指定图表的配置项和数据
               option = {
    		   title : {
                   subtext: dtime22,//'新增理财人数',
                   text: '新增理财人数（首次投资）'
               },
            tooltip : {
                trigger: 'axis',
                axisPointer : {            // 坐标轴指示器，坐标轴触发有效
                    type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
                }
            },
            legend: {
           	 x: 'center',
             y: 'bottom',
                data:[t1,t2,t3,t4],
                     
               // ['08-22--08-23-当天注册首次投资','08-22--08-23-前1天至前5天首次投资',
                // '08-22--08-23-前6天至前30天首次投资','08-22--08-23-前30天及更久时间首次投资',
                // '08-23--08-24-当天注册首次投资','08-23--08-24-前1天至前5天首次投资',
               //  '08-23--08-24-前6天至前30天首次投资','08-23--08-24-前30天及更久时间首次投资',
               // ]//['直接访问','邮件营销','联盟广告','视频广告','搜索引擎','百度','谷歌','必应','其他']
            },
            xAxis : [
                {
                    type : 'category',
                    data : ['定期宝','房宝宝','精英宝']   // ['周一','周二','周三','周四','周五','周六','周日']
                }
            ],
            yAxis : [
                {
                    type : 'value'
                }
            ],
            grid: {
                x: '8%',
                x2: '15',
                y2: '80',
                containLabel: true
            },
            series : [
                {
                    name:t1,//'08-22--08-23-当天注册首次投资',
                    type:'bar',
                    stack: '广告',
                    data:[dqb_countReg0Day, fbb_countReg0Day, jyb_countReg0Day]
                },
                {
                    name:t2,//'08-22--08-23-前1天至前5天首次投资',
                    type:'bar',
                    stack: '广告',
                    data:[dqb_countReg1To5, fbb_countReg1To5, jyb_countReg1To5]
                },
                {
                	
                    name:t3,//'08-22--08-23-前6天至前30天首次投资',
                    type:'bar',
//                    barWidth : 60,
                    stack: '广告',
                    data:[dqb_countReg6To30, fbb_countReg6To30, jyb_countReg6To30]
                },
                {
                	
                   name:t4,//'08-22--08-23-前30天及更久时间首次投资',
                    type:'bar',
                    stack: '广告',
                    data:[dqb_countReg31Plus, fbb_countReg31Plus, jyb_countReg31Plus]
                },
               
            ]
        };
                // 为echarts对象加载数据
                myChart.setOption(option);
                // 基于准备好的dom，初始化echarts图表
                var mynewChart = ec.init(document.getElementById('newfinancial1'));
                
                var records1 = <?=$this->records1?>;
              
                var dtime1 = <?=$this->dtime1?>;
                var dtime3 = {text:"<?=$this->dtime3;?>"};
                for(var tx1 in dtime3){
                    dtime33=dtime3[tx1];
                }
                //console.log(dtime3);
           
                var t1='当天注册';
                var t2='前1天至前5天';
                var t3='前6天至前30天';
                var t4='前30天及更久时间';

                if(records1==null){
                	tt1=dtime1+t1; tt2=dtime1+t2;
                    tt3=dtime1+t3; tt4=dtime1+t4;

                    fbb1_countReg0Day=0;
                    fbb1_countReg1To5=0;
                    fbb1_countReg6To30=0;
                    fbb1_countReg31Plus=0;

                    dqb1_countReg0Day=0;
                    dqb1_countReg1To5=0;
                    dqb1_countReg6To30=0;
                    dqb1_countReg31Plus=0;

                    jyb1_countReg0Day=0;
                    jyb1_countReg1To5=0;
                    jyb1_countReg6To30=0;
                    jyb1_countReg31Plus=0;
                    
                    }
                else{
                for(var dt1 in records1){
                    tt11=dt1+t1; tt22=dt1+t2;
                    tt33=dt1+t3; tt44=dt1+t4;
                   //fbb_countReg0Day=(parseInt(records[dt][fbb].countReg0Day);
                   fbb1_countReg0Day=parseInt(records1[dt1].fbb.countReg0Day);
                   fbb1_countReg1To5=parseInt(records1[dt1].fbb.countReg1To5);
                   fbb1_countReg6To30=parseInt(records1[dt1].fbb.countReg6To30);
                   fbb1_countReg31Plus=parseInt(records1[dt1].fbb.countReg31Plus);

                   dqb1_countReg0Day=parseInt(records1[dt1].dqb.countReg0Day);
                   dqb1_countReg1To5=parseInt(records1[dt1].dqb.countReg1To5);
                   dqb1_countReg6To30=parseInt(records1[dt1].dqb.countReg6To30);
                   dqb1_countReg31Plus=parseInt(records1[dt1].dqb.countReg31Plus);

                   jyb1_countReg0Day=parseInt(records1[dt1].jyb.countReg0Day);
                   jyb1_countReg1To5=parseInt(records1[dt1].jyb.countReg1To5);
                   jyb1_countReg6To30=parseInt(records1[dt1].jyb.countReg6To30);
                   jyb1_countReg31Plus=parseInt(records1[dt1].jyb.countReg31Plus);
                   
                   console.log(jyb1_countReg1To5);
                    }
                }
                

                // 指定图表的配置项和数据
               option = {
    		   title : {
                   subtext: dtime33,//'新增理财人数',
                   text: '新增理财人数（首次投资）'
               },
            tooltip : {
                trigger: 'axis',
                axisPointer : {            // 坐标轴指示器，坐标轴触发有效
                    type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
                }
            },
            legend: {
           	      x: 'center',
                  y: 'bottom',
                data:[t1,t2,t3,t4],
                     
               // ['08-22--08-23-当天注册首次投资','08-22--08-23-前1天至前5天首次投资',
                // '08-22--08-23-前6天至前30天首次投资','08-22--08-23-前30天及更久时间首次投资',
                // '08-23--08-24-当天注册首次投资','08-23--08-24-前1天至前5天首次投资',
               //  '08-23--08-24-前6天至前30天首次投资','08-23--08-24-前30天及更久时间首次投资',
               // ]//['直接访问','邮件营销','联盟广告','视频广告','搜索引擎','百度','谷歌','必应','其他']
            },
            grid: {
                x: '8%',
                x2: '15',
                y2: '80',
                containLabel: true
            },
            xAxis : [
                {
                    type : 'category',
                    data : ['定期宝','房宝宝','精英宝']   // ['周一','周二','周三','周四','周五','周六','周日']
                }
            ],
            yAxis : [
                {
                    type : 'value'
                }
            ],
            series : [

                {
                    name:t1,//'08-23--08-24-当天注册首次投资',
                    type:'bar',
                    stack: '搜索引擎',
                    data:[dqb1_countReg0Day, fbb1_countReg0Day, jyb1_countReg0Day]
                },
                {
                    name:t2,//'08-23--08-24-前1天至前5天首次投资',
                    type:'bar',
                    stack: '搜索引擎',
                    data:[dqb1_countReg1To5, fbb1_countReg1To5, jyb1_countReg1To5]
                },
                {
                    name:t3,//'08-23--08-24-前6天至前30天首次投资',
                    type:'bar',
                    stack: '搜索引擎',
                    data:[dqb1_countReg6To30, fbb1_countReg6To30, jyb1_countReg6To30]
                },
                 {
                    name:t4,//'08-23--08-24-前30天及更久时间首次投资',
                    type:'bar',
                    stack: '搜索引擎',
                    data:[dqb1_countReg31Plus, fbb1_countReg31Plus, jyb1_countReg31Plus]
                },
               
            ]
        };
                // 为echarts对象加载数据
               mynewChart.setOption(option);
            }
        );
    </script>
</div>