<div class="bjui-pageHeader">
    <form id="tabHistoryLogForm">
        <?php if ($hasManager == 1) {
            $mtRandId = '_' . mt_rand(10000, 99999);
            echo \Prj\Misc\View::mb_zzjgck('', '', $mtRandId);
            echo '<br />';
            echo '<label for="" style="margin-top: 7px;" id="zzjgLabel' . $mtRandId . '">' . $zzjgStr . '</label>';
            echo '<input type="hidden" id="zzjgName' . $mtRandId . '" name="zzjgName" value="' . $zzjgName . '">';
            echo '<input type="hidden" id="zzjgNameCh' . $mtRandId . '" name="zzjgNameCh" value="' . $zzjgNameCh . '">';
            echo '<br />';
        } ?>
        <label for="">开始日期</label>
        <input type="text" data-toggle="datepicker" name="startTime" size="14" value="<?php echo $this->startTime; ?>"/>
         <label for="">结束日期</label>
        <input type="text" data-toggle="datepicker" name="endTime" size="14" value="<?php echo $this->endTime; ?>"/>
        <button type="button" onclick="doLoad();" id="tabHistoryLogFormBtn" class="btn btn-default">查询</button>
    </form>
</div>
<div class="bjui-pageContent">
    <?php echo $view; ?>
</div>
<?php
if($Managerlogin==1){
    
}else{
    include dirname(__DIR__) . '/perfdst/comments.www.phtml';
}
?>

<script>
    function doLoad() {
        $(document).bjuiajax('doLoad', {
            target: '#list-tab',
            url: "<?php echo \Sooh\Base\Tools::uri(); ?>",
            data: $("#tabHistoryLogForm").serialize()
        });
    }

    mb_dept.callbackById["<?php echo $mtRandId;?>"] = function (obj) {
        
    	var obj_oaUser='';
      	var obj_zzjgName='';
        for (var oaUser in obj) {   
            obj_oaUser+=obj[oaUser]+',';
            obj_zzjgName+=oaUser+',';
        }

        obj_oaUser=(obj_oaUser.substring(obj_oaUser.length-1)==',')?obj_oaUser.substring(0,obj_oaUser.length-1):obj_oaUser;
        obj_zzjgName=(obj_zzjgName.substring(obj_zzjgName.length-1)==',')?obj_zzjgName.substring(0,obj_zzjgName.length-1):obj_zzjgName;
        
        $("#zzjgLabel<?php echo $mtRandId; ?>").text(obj_oaUser);
        $("#zzjgNameCh<?php echo $mtRandId; ?>").attr('value', obj_oaUser);
        $("#zzjgName<?php echo $mtRandId; ?>").attr('value', obj_zzjgName);
    };
</script>