<form action="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1), 'detail'); ?>" method="post" id="contracts-exportChecked" style="display: none;">
</form>
<div class="bjui-pageHeader">
    <form  id="pagerForm" method="get" action="<?php echo \Sooh\Base\Tools::uri(); ?>" data-toggle="ajaxsearch">
        <input type="hidden" name="__formguid__" value="default" />
        <input type="hidden" name="pageSize" value="<?php echo $this->pagesize; ?>">
        <input type="hidden" name="pageCurrent" value="<?php echo $this->pageid; ?>">
        <input type="hidden" name="orderField" value="${param.orderField}">
        <input type="hidden" name="orderDirection" value="${param.orderDirection}">
        <input type="hidden" name="ymdUsed" value="<?php echo $this->ymdUsed;?>">
        <div class="pull-right">
            <div class="btn-group">
                <button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">复选框-批量操作<span class="caret"></span></button>
                <ul class="dropdown-menu right" role="menu">
                    <li><a href="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1,'where'=>$this->where),'detail'); ?>">导出<span style="color: green;">全部</span></a></li>
<!--                    <li><a class="contracts-export" style="cursor: pointer">导出<span style="color: red">选中</span></a></li>-->
                    <li class="divider"></li>
                </ul>
            </div>

            <script>
                /** 构造表单 post 方法 提交 */
                var ids = new Array();
                $('.contracts-export').click(function(){
                    if(ids.length==0)
                    {
                        $(document).alertmsg('error', '无选中选项');
                        return false;
                    }
                    $('#contracts-exportChecked').html(''); //add ' '
                    for(var i in ids)
                    {
                        var reg = /function[.]*/;
                        if(reg.exec(ids[i])!=null)
                        {
                            continue;
                        }
                        $('#contracts-exportChecked').append("<input type='hidden' name='ids[]' value='"+ids[i]+"'>");
                    }
                    $('#contracts-exportChecked').submit();
                    return false;
                });
            </script>
        </div>
    </form>
</div>

<div class="bjui-pageContent">
<!--    <table class="table table-bordered table-hover table-striped">-->
    <table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true" data-toggle="tablefixed">
        <thead>
        <tr>
            <?php
            if(!empty($this->fieldsMap)) {
                foreach($this->fieldsMap as $title) {
                    ?>
                    <th ><?php echo $title; ?></th>
                    <?php
                }
            }

            ?>

        </tr>
        </thead>
        <tbody>
        <?php
        if(!empty($this->records)) {
            foreach($this->records as $r) {
                echo "<tr><td>";
                echo implode('</td><td>', $r);
                echo "</td>";
                echo "</tr>";
            }
        }
        ?>
        </tbody>
    </table>
</div>

<div class="bjui-pageFooter">
    <ul>
        <li><button type="button" class="btn-close" data-icon="close">关闭</button></li>
    </ul>
    <div class="pages">
        <span>每页&nbsp;</span>
        <div class="selectPagesize">
            <select data-toggle="selectpicker" data-toggle-change="changepagesize">
                <?php
                $pager = $this->pager;
                $r = explode(',', $pager->enumPagesize);
                foreach($r as $v){
                    $str .= "<option value=\"$v\">$v</option>";
                }
                echo $str;
                ?>
            </select>
        </div>
        <span>&nbsp;条，共 <?php echo $pager->total; ?> 条</span>
    </div>
    <div class="pagination-box" data-toggle="pagination" data-total="<?php echo $pager->total; ?>" data-page-size="<?php echo $pager->page_size; ?>" data-page-current="<?php $pager->pageid(); ?>"></div>

</div>
































