<div class="bjui-pageHeader">
    <?php
    $renderer = new \Prj\Misc\FormRenderer;
    $randNum = rand(1000,9999);
    echo $renderer->formForExport(Sooh\Base\Tools::uri([],'groundfinance'),$randNum);
    echo  $renderer->getSearchStandard(
        \Sooh\Base\Form\Broker::getCopy('default'),
        $renderer->getBatchArea(\Prj\Misc\View::btnEditInDatagrid('导入',Sooh\Base\Tools::uri([],'importground'),['width'=>1000,'height'=>800]).\Prj\Misc\View::btnDefaultInDatagrid('新增',Sooh\Base\Tools::uri([],'groundedit')), \Sooh\Base\Tools::uri(array('__EXCEL__'=>1,'where'=>$this->where),'groundfinance'), null)
    );
    ?>
</div>
<div class="bjui-pageContent tableContent">
    <table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true"
           data-toggle="tablefixed">
        <thead>
        <tr><?php
            $header = $this->header;
            if(!empty($header))
            {
                array_shift($header);
                foreach ($header as $k => $v) {
                    echo "<th width = '" . $v . "'>";
                    echo $k;
                    echo "</th>";
                }
            }

            ?>
            <th width="30"><?php echo \Prj\Misc\View::thCheckBox(); ?></th>
            <th width="100">操作</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $rs = $this->rs;
        //输出余额
        echo "<tr>";
        foreach($this->remains as $k=>$v){
            echo "<td style='background-color: #EAF1F6;font-weight: bold'>";
            echo $v;
            echo "</td>";
            if($k=='exp'){
                for($i=0;$i<3;$i++){
                    echo "<td style='background-color: #EAF1F6'></td>";
                }
            }
        }
        for($i=0;$i<4;$i++){
            echo "<td style='background-color: #EAF1F6'></td>";
        }
        echo "</tr>";
        if (!empty($rs)) {
            foreach ($rs as $r) {
                echo "<tr>";
                foreach ($r as $k => $v) {
                    if($k=='groundId')continue;
                    echo "<td>";
                    echo $v;
                    echo "</td>";
                }
                $_pkey_val_ = \Prj\Misc\View::encodePkey(['id'=>current($r)]);
                echo '<td>'.\Prj\Misc\View::trCheckBox($_pkey_val_).'</td>';
                echo "<td>";
                echo \Prj\Misc\View::btnDefaultInDatagrid('编辑',Sooh\Base\Tools::uri(['_pkey_val_'=>$_pkey_val_],'groundEdit'));
                echo "</td>";
                echo "</tr>";
            }
        }
        ?>
        </tbody>
    </table>
</div>
<div class="bjui-pageFooter"><?php echo \Prj\Misc\View::pagerStandard($this->pager);?></div>