<div class="pageContent">

		<div class="pageFormContent" layoutH="58">
			<table border="0" width="100%"><tr><td width="360" style="text-align:left"  valign="top">
			<?php echo "TODO"; ?>
			</td><td valign="top" style="text-align:left">
			<?php echo $this->inputRights; ?>
			</td></tr></table>
		</div>
		<div class="formBar">
			<ul>
				<li><div class="button"><div class="buttonContent"><button type="button" class="close">关闭</button></div></div></li>
			</ul>
		</div>
</div>