<div class="bjui-pageHeader">
    <form id="dayForm">
        <?php if ($hasManager == 1) {
            $mtRandId = '_' . mt_rand(10000, 99999);
            echo \Prj\Misc\View::mb_zzjgck('single', '', $mtRandId);
            echo '<br />';
            echo '<label for="" style="margin-top: 7px;" id="zzjgLabel' . $mtRandId . '">' . $zzjgStr . '</label>';
            echo '<input type="hidden" id="zzjgName' . $mtRandId . '" name="zzjgName" value="' . $zzjgName . '">';
            echo '<input type="hidden" id="zzjgNameCh' . $mtRandId . '" name="zzjgNameCh" value="' . $zzjgNameCh . '">';
            echo '<br />';
        } ?>
        <label for="">开始日期</label>
        <input type="text" data-toggle="datepicker" name="date" size="14" value="<?php echo $date; ?>"/>
        <button type="button" onclick="doLoad();" class="btn btn-default">查询</button>
    </form>
</div>
<div class="bjui-pageContent">
    <div class="col-md-8" style="min-height: 200px;">
        <?php echo $view->showPerf(); ?>
    </div>

    <div class="col-md-offset-1 text-center" style="width: 198px; float: left;">
        <div id="mb_cal" style="position:relative"></div>
    </div>
</div>
<?php
include "comments.www.phtml";
?>
<script>
    var zzjgInputs = new Array();
    mb_dept.callbackById["<?php echo $mtRandId;?>"] = function (obj) {
        var names = '', zzjgInputs = new Array();
        for (var oaUser in obj) {
            $("#zzjgLabel<?php echo $mtRandId; ?>").text(obj[oaUser]);
            $("#zzjgNameCh<?php echo $mtRandId; ?>").attr('value', obj[oaUser]);
            $("#zzjgName<?php echo $mtRandId; ?>").attr('value', oaUser);
        }
    };

    function doLoad() {
        $(document).bjuiajax('doLoad', {
            target: '#day-tab',
            url: "<?php echo \Sooh\Base\Tools::uri(); ?>",
            data: $("#dayForm").serialize()
        });
    }

    mb_week_back = function (date, func) {
        var url = '<?php echo \Sooh\Base\Tools::uri([], 'getdayset') ?>';
        var args = date;
        $.post(url, args, func);
    }
    mb_week_back_format = function (data) {
        var obj = data.data;
        var ret = new Array();
        for (var i in obj) {
            if (obj[i] == 1) {
                ret.push(i);
            }
        }
        return ret;
    }

    $('#mb_cal').datepicker({
//        mb_week_back : "mb_week_back", //周目标-点击回调函数
//        mb_week_back_format : "mb_week_back_format", //周目标-请求返回值的格式化函数
        mb_day_back: "mb_week_back", //日目标-点击回调函数
        mb_day_back_format: "mb_week_back_format", //日目标-请求返回值的格式化函数
        mb_fix: true //日期框不会消失
    });
</script>