<!--<meta http-equiv="refresh" content="5" url="http://10.1.1.212/plan/perfdst/tabday">-->
<div class="bjui-pageHeader">
    <form id="dayForm">
        <?php if ($hasManager == 1) {
            $mtRandId = '_' . mt_rand(10000, 99999);
            echo \Prj\Misc\View::mb_zzjgck('', '', $mtRandId, 1);
            echo '<br />';
            echo '<label for="" style="margin-top: 7px;" id="zzjgLabel' . $mtRandId . '">' . $zzjgStr . '</label>';
            echo '<br />';
            echo '<div id="gitLabDivtaday"></div>';
            echo '<input type="hidden" id="zzjgName' . $mtRandId . '" name="zzjgName" value="' . $zzjgName . '">';
            echo '<input type="hidden" id="zzjgNameCh' . $mtRandId . '" name="zzjgNameCh" value="' . $zzjgNameCh . '">';
            echo '<br />';
            }
           ?>

        <label for="">开始日期</label>
        <input type="text" data-toggle="datepicker" name="startDate" size="14" value="<?php echo $startDate ?>"/>
        <label for="">结束日期</label>
        <input type="text" data-toggle="datepicker" name="endDate" size="14" value="<?php echo $endDate ?>"/>
        <button type="button" onclick="doLoadDay();" class="btn btn-default">查询</button>
    </form>
</div>
<div class="bjui-pageContent">
    <div class="col-md-8" style="min-height: 200px;">
            <?php 
           echo $view;
            ?>
    </div>

    <div class="col-md-offset-1 text-center" style="width: 198px; float: left;">
        <div id="mb_cal" style="position:relative"></div>
    </div>
</div>
<?php
if($Managerlogin==1){

}else{
  include "comments.www.phtml";
}
?>
<script>
    var zzjgInputs = new Array();
    mb_dept.callbackById["<?php echo $mtRandId;?>"] = function (obj) {
        var names = '', zzjgInputs = new Array();
    	var obj_oaUser='';
      	var obj_zzjgName='';
        for (var oaUser in obj) {   
            obj_oaUser+=obj[oaUser]+',';
            obj_zzjgName+=oaUser+',';
        }

        setSelectedUsers( 1, obj_zzjgName );

        obj_oaUser=(obj_oaUser.substring(obj_oaUser.length-1)==',')?obj_oaUser.substring(0,obj_oaUser.length-1):obj_oaUser;
        obj_zzjgName=(obj_zzjgName.substring(obj_zzjgName.length-1)==',')?obj_zzjgName.substring(0,obj_zzjgName.length-1):obj_zzjgName;
        
        $("#zzjgLabel<?php echo $mtRandId; ?>").text(obj_oaUser);
        $("#zzjgNameCh<?php echo $mtRandId; ?>").attr('value', obj_oaUser);
        $("#zzjgName<?php echo $mtRandId; ?>").attr('value', obj_zzjgName);

        var checkname=[
                       "卢秋鹤","向兰英","吴鹏",
                       "戴杰","李梦竹","李连奇",
                       "梁言庆","汤高航","沈海燮",
                       "王伟","王阳","童益丰","钟继业",
                       "陶满","马龙龙","张有传","赵闯",
                       "马天一","孔子龙","徐利营","赵宇光",
                       "周豪","孙瑞明","宋威",
                       "岳化梦","李向南","李增芳","李晓苑",
                       "杨丽雲","汪杰","熊彩阳","金超","牛鹏凯",
                   ];
          
           var username = obj[oaUser]; 
           var temp = username.split("--");
          // alert(temp);
           var location=checkname.indexOf(temp[0]);
          // alert(location);
           if(false&&location>=0) {
              // alert("121");
         	  //显示
        	 $("#gitLabDivtaday").empty("");
        	   
          	 $("#gitLabDivtaday").append("<a id=\"gitLabDivtaday\"  class=\"btn btn-blue\" href=\"http://rpt.kuaikuaidai.com/index/gitlab/index?userId="+temp[0]+"\" target=\"_blank\">点击查看工作目标</a>");
             
           } else {
          	    //隐藏
               $("#gitLabDivtaday").empty();
              
           }
           
    };

    function doLoadDay() {
        $(document).bjuiajax('doLoad', {
            target: '#day-tab',
            url: "<?php echo \Sooh\Base\Tools::uri(); ?>",
            data: $("#dayForm").serialize()
        });
    }

    mb_week_back = function (date, func) {
        var url = '<?php echo \Sooh\Base\Tools::uri([], 'getdayset') ?>';
        var args = date;
        $.post(url, args, func);
    }
    mb_week_back_format = function (data) {
        var obj = data.data;
        var ret = new Array();
        for (var i in obj) {
            if (obj[i] == 1) {
                ret.push(i);
            }
        }
        return ret;
    }

    $('#mb_cal').datepicker({
//        mb_week_back : "mb_week_back", //周目标-点击回调函数
//        mb_week_back_format : "mb_week_back_format", //周目标-请求返回值的格式化函数
        mb_day_back: "mb_week_back", //日目标-点击回调函数
        mb_day_back_format: "mb_week_back_format", //日目标-请求返回值的格式化函数
        mb_fix: true //日期框不会消失
    });
</script>