<form action="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1, 'where'=>$this->where),'index'); ?>" method="post" id="contracts-exportChecked" style="display: none;">
</form>
<div class="bjui-pageHeader">
   <form  id="pagerForm" method="get" action="<?php echo \Sooh\Base\Tools::uri(); ?>" data-toggle="ajaxsearch">
        <input type="hidden" name="__formguid__" value="default" />
        <input type="hidden" name="pageSize" value="<?php echo $this->pagesize; ?>">
        <input type="hidden" name="pageCurrent" value="<?php echo $this->pageid; ?>">
        <input type="hidden" name="orderField" value="${param.orderField}">
        <input type="hidden" name="orderDirection" value="${param.orderDirection}">
        <label>起始日期：</label>
        <input type="text" data-toggle="datepicker" name="ymdFrom" value="<?php echo $this->ymdFrom; ?>" size="18" data-pattern="yyyy-MM"  />
        &nbsp;
        <label>截止日期：</label>
        <input type="text" data-toggle="datepicker" name="ymdTo" value="<?php echo $this->ymdTo; ?>" size="18" data-pattern="yyyy-MM"/>
        <button type="submit" class="btn btn-default">查询</button>
        <a class="btn btn-orange" href="javascript:;" data-toggle="reloadsearch" data-clear-query="true" data-icon="undo">清空查询</a>
        <br />
        <lalbel>
            <span style="font-size: 14px; font-weight:700">合计:</span>
            <span style="font-size:13px;line-height: 40px;">
                超级用户总充值<span style="color: red;"><?php echo($this->superuesrrecharge)?$this->superuesrrecharge:0;?></span>元,&nbsp;超级用户总提现<span style="color: red;"><?php echo($this->superuesrwithdraw)?$this->superuesrwithdraw:0;?></span>元,&nbsp;
                普通用户总充值<span style="color: red;"><?php echo($this->normaluesrrecharge)?$this->normaluesrrecharge:0;?></span>元,&nbsp;普通用户总提现<span style="color: red;"><?php echo($this->normaluesrwithdraw)?$this->normaluesrwithdraw:0;?></span>元,&nbsp;
                总充值<span style="color: red;"><?php echo($this->rechargeAmount)?$this->rechargeAmount:0;?></span>元,&nbsp;总提现<span style="color: red;"><?php echo($this->withdrawAmount)?$this->withdrawAmount:0;?></span>元
            <span>
        </lalbel>
    
   <div class="pull-right">
   
    <div class="btn-group">
            <button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">批量操作<span class="caret"></span></button>
            <ul class="dropdown-menu right" role="menu">
                <li><a  href="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1,'where'=>$this->where),'index'); ?>">导出<span style="color: green;">当前页全部</span></a></li>
            </ul>
        </div>
        <script>
            /*
             构造表单 post 方法 提交
             */
            var ids = new Array();
            $('.contracts-export').click(function(){
                if(ids.length==0)
                {
                    $(document).alertmsg('error', '无选中选项');
                    return false;
                }
                $('#contracts-exportChecked').html(''); //add ' '
                for(var i in ids)
                {
                    var reg = /function[.]*/;
                    if(reg.exec(ids[i])!=null)
                    {
                        continue;
                    }
                    $('#contracts-exportChecked').append("<input type='hidden' name='ids[]' value='"+ids[i]+"'>");
                }
                $('#contracts-exportChecked').submit();
                //window.location.href="/index.php?__=manage/managers/index&__EXCEL__=1&ids="+ids;
                return false;
            });
        </script>
    </div>
    </form>
</div>
<div class="bjui-pageContent tableContent">
    <table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true">
        <thead>
        <tr>
            <?php $headers=$this->headers;
            foreach($headers as $k=>$v){
                echo "<th width=\"$v\">$k</th>";
            }
            ?>
            <!--<th width="26"><input type="checkbox" class="checkboxCtrl" data-group="ids" data-toggle="icheck"></th>-->
             <th width="100">操作</th>
             
        </tr>
        </thead>
        <tbody>
        <?php $records=$this->records;
        if (!empty($records)){
            foreach ($records as $r){
                $_pkey_ = $r['ym'];
               // var_log($_pkey_,'pke>>>>>>>>>>');
                
                echo "<tr data-id=\"{$_pkey_}\">";
                unset ($r['_pkey_']);
                echo '<td>';
                echo implode('</td><td>', $r);
                echo '</td>';
                echo '<td>';     
                echo \Prj\Misc\View::btnDefaultInDatagrid('日用户充值/提现统计',  \Sooh\Base\Tools::uri(['_pkey_val_'=>$_pkey_],'rechdrawday'));
                echo '</td>';
                echo '</tr>'."\n";
              
            }
        }
        ?>
        </tbody>
    </table>
</div>
<div class="bjui-pageFooter">
    <ul>
        <li><button type="button" class="btn-close" data-icon="close">关闭</button></li>
    </ul>
    <div class="pages">
        <span>每页&nbsp;</span>
        <div class="selectPagesize">
            <select data-toggle="selectpicker" data-toggle-change="changepagesize">
                <?php
                $pager = $this->pager;
                
                $r = explode(',', $pager->enumPagesize);
                //var_log($pager,'pager>>>>>>>>>>>>>>');
                foreach($r as $v){
                    $str .= "<option value=\"$v\">$v</option>";
                }
                echo $str;
                ?>
            </select>
        </div>
        <span>&nbsp;条，共 <?php echo $pager->total; ?> 条</span>
    </div>
       <div class="pagination-box" data-toggle="pagination" data-total="<?php echo $pager->total; ?>" data-page-size="<?php echo $pager->page_size; ?>" data-page-current="<?php echo $pager->pageid(); ?>"></div>

</div>



