<!-- 查询表单 -->
<form action="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1),'index'); ?>" method="post" id="contracts-exportChecked" style="display: none;">
</form>
<div class="bjui-pageHeader">
    <?php
    if($this->_type!='ajax') {
        ?>
        <form id="pagerForm" method="get" action="<?php echo \Sooh\Base\Tools::uri(); ?>" data-toggle="ajaxsearch">
            <!--        <input type="hidden" name="__formguid__" value="default" />-->
            <input type="hidden" name="pageSize" value="<?php echo $this->pagesize; ?>">
            <input type="hidden" name="pageCurrent" value="<?php echo $this->pageid; ?>">
            <input type="hidden" name="orderField" value="${param.orderField}">
            <input type="hidden" name="orderDirection" value="${param.orderDirection}">
            <label>投资起始日期从：</label>
            <input type="text" data-toggle="datepicker" name="ymdFrom" value="<?php echo $this->ymdFrom; ?>" size="18"/>
            <label>到：</label>
            <input type="text" data-toggle="datepicker" name="ymdTo" value="<?php echo $this->ymdTo; ?>" size="18"/>&nbsp;

            <label>合同编号:</label>
            <input type="text" name="touzihetongbianhao" value="<?php echo $this->touzihetongbianhao; ?>" size="18"/>&nbsp;


            <label>结清情况：</label>
            <select name="selectedJieqingqingkuang">
                <?php
                if ($this->selectedJieqingqingkuang === NULL) {
                    $this->selectedJieqingqingkuang = 0;
                }
                foreach ($this->jieqingqingkuang as $k => $v) {
                    echo "<option value=\"$k\" " . ($this->selectedJieqingqingkuang == $k ? 'selected="selected"' : '') . ">" . $v . "</option>";
                }
                ?>
            </select>&nbsp;


            <lable>投资人:</lable>
            <input type="text" name="touziren" value="<?php echo $this->touziren; ?>" size="18"/>&nbsp;

            <button type="submit" class="btn btn-default">查询</button>
            &nbsp;
            <a class="btn btn-orange" href="javascript:;" data-toggle="reloadsearch" data-clear-query="true"
               data-icon="undo">清空查询</a>

            <div class="pull-right">
                <div class="btn-group">
                 <?php
    		      echo \Prj\Misc\View::btnImportInDatagrid(\Sooh\Base\Tools::uri(null,'import'));
    		      ?>
                    <!--<button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">
                        复选框-批量操作<span class="caret"></span></button>
                    <ul class="dropdown-menu right" role="menu">
                        <li>
                            <a href="<?php //echo \Sooh\Base\Tools::uri(array('__EXCEL__' => 1, 'where' => $this->where), 'index'); ?>">导出<span
                                    style="color: green;">全部</span></a></li>
                        <!--                    <li><a class="contracts-export" style="cursor: pointer">导出<span style="color: red">选中</span></a></li>-->
                        <!--<li class="divider"></li>
                    </ul>-->
             &nbsp; &nbsp; &nbsp; &nbsp;
            </div class="btn-group">
             <button type="button" class="btn-red">
		      <a href="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1,'where'=> $this->where),'export'); ?>"><span style="color: orange;">导出全部</span></a>
		      </button>
		      
            <div>    
                </div>
            </div>
        </form>
        <?php
    }
    ?>
</div>

<?php
$view = $this->view;
//var_log($view, 'view#########');
$view->show();
?>