<div class="bjui-pageHeader">
    <form  id="pagerForm" method="get" action="<?php echo \Sooh\Base\Tools::uri(); ?>" data-toggle="ajaxsearch">
        <label>时间从：</label>
        <input id="inputYmdFrom" type="text" data-toggle="datepicker" name="ymdFrom" value="<?php echo ($this->ymdFrom?$this->ymdFrom:date('Y-m-d', time()-7*86400)); ?>" size="18" />
        <label>时间到：</label>
        <input id="inputYmdTo" type="text" data-toggle="datepicker" name="ymdTo" value="<?php echo ($this->ymdTo?$this->ymdTo:date('Y-m-d', time()-86400)); ?>" size="18" />
        <label>渠道选择:</label>
        <select name="selectedContractId">
            <?php
            $contractIds = $this->contractIds;
            if($this->selectedContractId===NULL) {
                $this->selectedContractId='ALLCONTRACTS';
            }
            foreach($contractIds as $cid => $remark){
                echo "<option value=\"$cid\" ".($this->selectedContractId==$cid?'selected="selected"':'').">".$remark."</option>";
            }
            ?>
        </select>
        <input type="hidden" name="__VIEW__" value="<?php echo $this->_view;?>" size="18" />
        <button type="submit" class="btn btn-default">查询</button>
        &nbsp;
        <label style="color:red;"><?php echo $this->errMsg;?></label>
    </form>
</div>

<div class="bjui-pageContent">
    <div id="regtoinvestmentrate" style="height:400px"></div>
    <script type="text/javascript">
        require.config({
            paths:{
                echarts: '/echarts/dist'
            }
        });

        require(
            [
                'echarts',
                'echarts/chart/bar', // 使用柱状图就加载bar模块，按需加载
                'echarts/chart/line' // 使用柱状图就加载bar模块，按需加载
            ],
            function (ec) {
                // 基于准备好的dom，初始化echarts图表
                var myChart = ec.init(document.getElementById('regtoinvestmentrate'));
                var category = <?=$this->category;?>;
                var rs=<?=$this->rs;?>;
                var legendData = <?=$this->legendData;?>;
                var xAxisData = [];
                var legend = [];
                var series = [];
                for (var k in category) {
                    if(typeof(category[k]) == 'function'){
                        continue;
                    }
                    xAxisData.push(category[k]);
                }

                for (var k in legendData) {
                    if(typeof(legendData[k]) == 'function'){
                        continue;
                    }
                    legend.push(legendData[k]);
                }

                for(var dt in rs) {
                    var data = {
                        name:dt,
                        type:'bar',
                        itemStyle : { normal: {label : {show: true, formatter: '{c}%', position: 'top'}}},
                        data:[ rs[dt].realnameCount, rs[dt].bindcardCount, rs[dt].newRechargeCount,  rs[dt].newBuyCount ]
                    };
                    series.push(data);
                }
//console.log(series);
                option = {
                    title : {
                        text: "注册至理财转化率（当日注册）",
                        subtext: ''
                    },
                    tooltip : {
                        trigger: 'axis'
                    },
                    legend: {
                    	x: 'center',
                        y: 'bottom',
                        data:legend //['8.23-8.24','8.25-8.26']
                    },
                    xAxis : [
                        {
                            type : 'category',
                            data : xAxisData,
                            axisLabel : {
                                interval : 0,
                                rotate : 45
                            }
                        }
                    ],
                    yAxis : [
                        {
                            type : 'value',
                            axisLabel:{formatter: '{value}%'}
                        }
                    ],
                    grid: {
                        x: '12%',
                        x2: '15',
                        y2: '110',
                        containLabel: true
                    },
                    series:series
                };

                // 为echarts对象加载数据
                myChart.setOption(option);
            }
        );

    </script>


</div>