<?php 
//error_log("manager->index:useTpl:".$this->useTpl);
switch($this->useTpl){
	case 'logout':
		$this->flgIsSinglePage=true;
		$this->htmlHeadPart('<title>后台管理系统</title>');
		echo $this->renderInc('head');
		echo '<body scroll="no">';
		include "auto/logout.www.phtml";
		break;
	
	
	case 'homepage':
//		$this->flgIsSinglePage=false;
//		$this->htmlHeadPart('<title>后台管理系统</title>');
//		echo $this->renderInc('head');
//		echo '<body scroll="no">';
		include "auto/homepage.www.phtml";
		break;
	
	
	case 'login':
		$this->flgIsSinglePage=true;
		$this->htmlHeadPart('<title>后台管理系统</title>');
		echo $this->renderInc('head');
		echo '<body scroll="no">';
		include "auto/login.www.phtml";
		break;
	
	default:
		$this->htmlHeadPart('<title>后台管理系统</title>');
		echo $this->renderInc('head');
		echo '<body>';
		echo "unknown auto-index";
		break;
}
echo "<div style=\"clear:both;\"></div></body></html>";