<br/><br/><br/><br/><center><div defh="150" class="panel" style="display: block;width:400px;">
		<div class="panelHeader"><div class="panelHeaderContent"><h1 style="cursor: move;"> </h1></div></div>
		<div class="panelContent" style="height: 150px;">
	<div class="pageContent" >
			<div class="pageFormContent" layoutH="58"><br/><br/>
				您已退出系统。<a href="<?php echo \Sooh\Base\Tools::uri(null, 'login', 'manager'); ?>"><u>重新登入</u></a>
			</div>
	</div>
</div><div class="panelFooter"><div class="panelFooterContent"></div></div></div></center>