CREATE TABLE `fk_liuchengdan` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `hetongbianhao` varchar(50) NOT NULL DEFAULT '' COMMENT '合同编号',
  `jiekuanren` varchar(30) NOT NULL DEFAULT '' COMMENT '借款人',
  `pipeizijinqingkuang` tinyint(4) NOT NULL DEFAULT '0' COMMENT '匹配资金情况  0 未匹配, 1 已匹配',
  `fangkuanshijian` int(11) NOT NULL DEFAULT '0' COMMENT '放款时间',
  `xianxiayifangkuan` tinyint(4) NOT NULL DEFAULT '0' COMMENT '线下已放款 0 否, 1 是',
  `fangkuanshijian8` int(11) NOT NULL DEFAULT '0' COMMENT '放款时间8',
  `xianshangyifangkuan` tinyint(4) NOT NULL DEFAULT '0' COMMENT '线上已放款 0 否, 1 是',
  `fangkuanshijian10` int(11) NOT NULL DEFAULT '0' COMMENT '放款时间10',
  `jibenxinxiyilu` tinyint(4) NOT NULL DEFAULT '0' COMMENT '基本信息已录 0 否, 1 是',
  `chulishijian` int(11) NOT NULL DEFAULT '0' COMMENT '处理时间',
  `xiangxixinxiyilu` tinyint(4) NOT NULL DEFAULT '0' COMMENT '详细信息已录 0 否, 1 是',
  `chulishijian14` int(11) NOT NULL DEFAULT '0' COMMENT '处理时间14',
  `tijiangyihesuan` tinyint(4) NOT NULL DEFAULT '0' COMMENT '提奖已核算 0 否, 1 是',
  `chulishijian16` int(11) NOT NULL DEFAULT '0' COMMENT '处理时间16',
  `xiangmuyiguidang` tinyint(4) NOT NULL DEFAULT '0' COMMENT '项目已归档 0 否, 1 是',
  `chulishijian18` int(11) NOT NULL DEFAULT '0' COMMENT '处理时间18',
  `yishenhe` tinyint(4) NOT NULL DEFAULT '0' COMMENT '已审核 0 否, 1 是',
  `chulishijian20` int(11) NOT NULL DEFAULT '0' COMMENT '处理时间20',
  PRIMARY KEY (`id`),
  UNIQUE KEY `liuchengdan_hetongbianhao` (`hetongbianhao`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='流程单';

CREATE TABLE `fk_rongzixiangmubiao` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
    `rongzihetongbianhao` varchar(40) NOT NULL DEFAULT '' COMMENT '融资合同编号',
    `jiekuanren` varchar(80) NOT NULL DEFAULT '' COMMENT '借款人',
    `diyaren` varchar(80) NOT NULL DEFAULT '' COMMENT '抵押人',
    `baozhengren` varchar(80) NOT NULL DEFAULT '' COMMENT '保证人',
    `lianxidianhua` varchar(255) NOT NULL DEFAULT '' COMMENT '联系电话',
    `bianhao` int(11) NOT NULL DEFAULT 0 COMMENT '编号',
    `jiekuanewanyuan` int(11) NOT NULL DEFAULT 0 COMMENT '借款额[分]',
    `qishiriqi` int(11) NOT NULL DEFAULT 0 COMMENT '起始日期',
    `yue` tinyint(4) NOT NULL DEFAULT 0 COMMENT '月',
    `tian` tinyint(4) NOT NULL DEFAULT 0 COMMENT '天',
    `daoqiriqi` int(11) NOT NULL DEFAULT 0 COMMENT '到期日期',
    `fuxifeifangshi` varchar(40) NOT NULL DEFAULT '' COMMENT '付息费方式',
    `fuxiri` varchar(40) NOT NULL DEFAULT '' COMMENT '付息日',
    `yewuleixing` varchar(40) NOT NULL DEFAULT '' COMMENT '业务类型',
    `kehuleixing` varchar(40) NOT NULL DEFAULT '' COMMENT '客户类型',
    `kehulaiyuan` varchar(40) NOT NULL DEFAULT '' COMMENT '客户来源',
    `lixiyue` int(11) NOT NULL DEFAULT 0 COMMENT '利息_月[%]',
    `lixiyingshou` int(11) NOT NULL DEFAULT 0 COMMENT '利息_应收[%]',
    `lixiyingshouyuan` int(11) NOT NULL DEFAULT 0 COMMENT '利息_应收[元]',
    `lixishishouyuan` int(11) NOT NULL DEFAULT 0 COMMENT '利息_实收[元]',
    `fuwufeianyue` int(11) NOT NULL DEFAULT 0 COMMENT '服务费_按月[%]',
    `fuwufeiyicixingyue` int(11) NOT NULL DEFAULT 0 COMMENT '服务费_一次性[%/月]',
    `fuwufeiyingshouyuan` int(11) NOT NULL DEFAULT 0 COMMENT '服务费_应收[元]',
    `fuwufeishishouyuan` int(11) NOT NULL DEFAULT 0 COMMENT '服务费_实收[元]',
    `dianzifeijineyuan` int(11) NOT NULL DEFAULT 0 COMMENT '垫资费_金额[元]',
    `dianzifeibilv` int(11) NOT NULL DEFAULT 0 COMMENT '垫资费_比率[%]',
    `zhongjiefeiyue` int(11) NOT NULL DEFAULT 0 COMMENT '中介费_月[%]',
    `zhongjiefeizong` int(11) NOT NULL DEFAULT 0 COMMENT '中介费_总[%]',
    `zhongjiefeiyingshouyuan` int(11) NOT NULL DEFAULT 0 COMMENT '中介费_应收[元]',
    `zhongjiefeishishouyuan` int(11) NOT NULL DEFAULT 0 COMMENT '中介费_实收[元]',
    `zongheyue` int(11) NOT NULL DEFAULT 0 COMMENT '综合[%/月]',
    `yuexifeilv` int(11) NOT NULL DEFAULT 0 COMMENT '月息费率[%]',
    `baozhengjin` int(11) NOT NULL DEFAULT 0 COMMENT '保证金[%]',
    `baozhengjinyuan` int(11) NOT NULL DEFAULT 0 COMMENT '保证金[元]',
    `fangchanleixing` varchar(40) NOT NULL DEFAULT '' COMMENT '房产类型',
    `fangchanquyu` varchar(40) NOT NULL DEFAULT '' COMMENT '房产区域',
    `fangchanweizhi` varchar(80) NOT NULL DEFAULT '' COMMENT '房产位置',
    `gongzheng` tinyint(4) NOT NULL DEFAULT 0 COMMENT '公证',
    `quanweidaoqiri` int(11) NOT NULL DEFAULT 0 COMMENT '全委[到期日]',
    `fangkuanrenyinhang` int(11) NOT NULL DEFAULT 0 COMMENT '放款人[银行]',
    `kehujingli` int(11) NOT NULL DEFAULT 0 COMMENT '客户经理',
    `tuandui` varchar(40) NOT NULL DEFAULT '' COMMENT '团队',
    `fengkongjingli` varchar(80) NOT NULL DEFAULT '' COMMENT '风控经理',
    `jieqingqingkuang` tinyint(4) NOT NULL DEFAULT 0 COMMENT '结清情况',
    `jieqingriqi` int(11) NOT NULL DEFAULT 0 COMMENT '结清日期',
    `beizhu` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
    `status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '状态位',
    `createTime` int(11) NOT NULL DEFAULT 0 COMMENT '创建时间',
    `updateTime` int(11) NOT NULL DEFAULT 0 COMMENT '最后更新时间',
    `iRecordVerID` int(11) NOT NULL DEFAULT 0,
    `sLockData` varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='融资项目表';

DROP TABLE IF EXISTS `fk_xianshangbenxifeizhang`;
CREATE TABLE `fk_xianxiabenxifeizhang` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `rongzihetongbianhao` varchar(40) NOT NULL DEFAULT '' COMMENT '融资合同编号',
  `jiekuanren` varchar(40) NOT NULL DEFAULT '' COMMENT '借款人',
  `qishu` tinyint(4) NOT NULL DEFAULT '0' COMMENT '期数',
  `zhonglei` varchar(40) NOT NULL DEFAULT '' COMMENT '种类',
  `yingfujineyuan` int(11) NOT NULL DEFAULT '0' COMMENT '应付金额[元]',
  `yingfushijian` int(11) NOT NULL DEFAULT '0' COMMENT '应付时间',
  `yifujineyuan` varchar(40) NOT NULL DEFAULT '' COMMENT '已付金额[元]',
  `qianfuyincang` varchar(40) NOT NULL DEFAULT '' COMMENT '欠付[隐藏]',
  `yuqitianshu` varchar(40) NOT NULL DEFAULT '' COMMENT '逾期天数',
  `yuqililv` varchar(40) NOT NULL DEFAULT '' COMMENT '逾期利率[%]',
  `yuqifeiyuan` varchar(40) NOT NULL DEFAULT '' COMMENT '逾期费[元]',
  `qianfujineyuan` varchar(40) NOT NULL DEFAULT '' COMMENT '欠付金额[元]',
  `beizhu` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `iRecordVerID` int(11) NOT NULL DEFAULT '0',
  `sLockData` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='线下本息费账';


drop table if EXISTS `fk_xianxiarijizhang`;
CREATE TABLE `fk_xianxiarijizhang` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `riqi` int(11) NOT NULL DEFAULT '0' COMMENT '日期',
  `zhonglei` tinyint(4) NOT NULL DEFAULT '0' COMMENT '种类',
  `hetongbianhao` varchar(40) NOT NULL DEFAULT '' COMMENT '合同编号',
  `kehu` varchar(40) NOT NULL DEFAULT '' COMMENT '客户',
  `jineyuan` bigint(20) NOT NULL DEFAULT '0' COMMENT '金额[元]',
  `zhanghu` int(11) NOT NULL DEFAULT '0' COMMENT '账户',
  `beizhu` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `createTime` int(11) NOT NULL DEFAULT '0' COMMENT '记录添加时间',
  `updateTime` int(11) NOT NULL DEFAULT '0' COMMENT '记录更新时间',
  `iRecordVerID` int(11) NOT NULL DEFAULT '0',
  `sLockData` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='线下日记账';

CREATE TABLE `fk_rongzidangan` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
    `rongzihetongbianhao` int(11) DEFAULT 0 NOT NULL COMMENT '融资合同编号',
    `jiekuanren` varchar(80) DEFAULT '' NOT NULL COMMENT '借款人',
    `jiekuanjinewanyuan` int(11) DEFAULT 0 NOT NULL COMMENT '借款金额[分]',
    `yewuleixing` tinyint(4) DEFAULT 0 NOT NULL COMMENT '业务类型',
    `danganbianhao` varchar(40) DEFAULT '' NOT NULL COMMENT '档案编号',
    `fangchanzhengliuzhi` tinyint(4) DEFAULT 0 NOT NULL COMMENT '房产证留置',
    `qitaliuzhiwu` varchar(255) DEFAULT '' NOT NULL COMMENT '其他留置物',
    `chanquanren` varchar(255) DEFAULT '' NOT NULL COMMENT '产权人',
    `fangchandizhi` varchar(255) DEFAULT '' NOT NULL COMMENT '房产地址',
    `fangchanzhengbianhao` varchar(255) DEFAULT '' NOT NULL COMMENT '房产证编号',
    `taxiangquanzhengbianhao` varchar(255) DEFAULT '' NOT NULL COMMENT '他项权证编号',
    `tazhengqishiri` int(11) DEFAULT 0 NOT NULL COMMENT '他证起始日',
    `tazhengdaoqiri` int(11) DEFAULT 0 NOT NULL COMMENT '他证到期日',
    `jiekuanhetong` tinyint(4) DEFAULT 0 NOT NULL COMMENT '借款合同',
    `buchongxieyi` tinyint(4) DEFAULT 0 NOT NULL COMMENT '补充协议',
    `zhuanzhangpingtiao` tinyint(4) DEFAULT 0 NOT NULL COMMENT '转账凭条',
    `qitaziliao` tinyint(4) DEFAULT 0 NOT NULL COMMENT '其他资料',
    `tazhengzhuxiaoshijian` int(11) DEFAULT 0 NOT NULL COMMENT '他证注销时间',
    `beizhu` varchar(255) DEFAULT '' NOT NULL COMMENT '备注',
    `createTime` int(11) DEFAULT 0 NOT NULL COMMENT '创建时间',
    `updateTime` int(11) DEFAULT 0 NOT NULL COMMENT '更新时间',
    `status` tinyint(4) DEFAULT 0 NOT NULL COMMENT '状态位',
    `iRecordVerID` int(11) NOT NULL DEFAULT 0,
    `sLockData` varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='融资档案';

DROP TABLE IF EXISTS `fk_rongzikehumingce`;
CREATE TABLE `fk_rongzikehumingce` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `bianhao` int(11) NOT NULL DEFAULT '0' COMMENT '编号',
  `xingming` varchar(40) DEFAULT '' COMMENT '姓名',
  `weihuren` varchar(40) DEFAULT '' COMMENT '维护人',
  `guishuren` varchar(40) DEFAULT '' COMMENT '归属人',
  `yuanguishu` varchar(40) DEFAULT '' COMMENT '原归属',
  `jieshaoren` varchar(40) DEFAULT '' COMMENT '介绍人',
  `zaibaoqingkuang` tinyint(4) DEFAULT '0' COMMENT '在保情况',
  `jieqingriqi` varchar(16) DEFAULT '' COMMENT '结清日期',
  `iRecordVerID` int(11) NOT NULL DEFAULT '0',
  `sLockData` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `rongzikehumingce_xingming` (`xingming`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='融资客户名册';


drop table IF EXISTS `fk_rongrenqixinxi`;
CREATE TABLE `fk_rongrenqixinxi` (
  `kehubianhao` int(11) NOT NULL AUTO_INCREMENT COMMENT '客户编号',
  `kehu` varchar(40) NOT NULL DEFAULT '' COMMENT '客户',
  `leixing` tinyint(4) NOT NULL DEFAULT '0' COMMENT '类型',
  `ming` varchar(80) NOT NULL DEFAULT '' COMMENT '名',
  `guanxi` varchar(40) NOT NULL DEFAULT '' COMMENT '关系',
  `zhengjianhaoma` varchar(255) NOT NULL DEFAULT '' COMMENT '证件号码',
  `xingbie` varchar(2) NOT NULL DEFAULT '-' COMMENT '性别',
  `nianling` int(11) NOT NULL DEFAULT '0' COMMENT '年龄',
  `hunyinzhuangkuang` varchar(40) NOT NULL DEFAULT '' COMMENT '婚姻状况',
  `lianxidianhua` varchar(255) NOT NULL DEFAULT '' COMMENT '联系电话',
  `xianzhuzhi` varchar(255) NOT NULL DEFAULT '' COMMENT '现住址',
  `hujidi` varchar(255) NOT NULL DEFAULT '' COMMENT '户籍地',
  `gongzuodanwei` varchar(255) NOT NULL DEFAULT '' COMMENT '工作单位',
  `danweidizhi` varchar(255) NOT NULL DEFAULT '' COMMENT '单位地址',
  `fadingdaibiaoren` varchar(40) NOT NULL DEFAULT '' COMMENT '法定代表人',
  `shijikongzhiren` varchar(40) NOT NULL DEFAULT '' COMMENT '实际控制人',
  `guquanjiegou` varchar(255) NOT NULL DEFAULT '' COMMENT '股权结构',
  `bangongdizhi` varchar(255) NOT NULL DEFAULT '' COMMENT '办公地址',
  `beizhixingchaxunshijian` int(11) NOT NULL DEFAULT '0' COMMENT '被执行查询时间',
  `zhengxinchaxunshijian` int(11) NOT NULL DEFAULT '0' COMMENT '征信查询时间',
  `beizhu` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `createTime` int(11) NOT NULL DEFAULT '0' COMMENT '记录添加时间',
  `updateTime` int(11) NOT NULL DEFAULT '0' COMMENT '记录更新时间',
  `iRecordVerID` int(11) NOT NULL DEFAULT '0',
  `sLockData` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`kehubianhao`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='融人企信息';

CREATE TABLE `fk_rongfangchanxinxi` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
    `kehubianhao` varchar(255) DEFAULT 0 NOT NULL COMMENT '客户编号',
    `kehu` varchar(40) DEFAULT '' NOT NULL COMMENT '客户',
    `fangchanquyu` tinyint(4) DEFAULT 0 NOT NULL COMMENT '房产区域',
    `fangchandizhi` varchar(255) DEFAULT '' NOT NULL COMMENT '房产地址',
    `chanquanren` varchar(40) DEFAULT '' NOT NULL COMMENT '产权人',
    `mianji` int(11) DEFAULT 0 NOT NULL COMMENT '面积[㎡]/100',
    `fangchanleixing` tinyint(4) DEFAULT 0 NOT NULL COMMENT '房产类型',
    `shifouxuweihu` tinyint(4) DEFAULT 0 NOT NULL COMMENT '是否需维护',
    `shifoudiya` tinyint(4) DEFAULT 0 NOT NULL COMMENT '是否抵押',
    `pingguzhiwanyuan` int(11) DEFAULT 0 NOT NULL COMMENT '评估值[分]',
    `pinggushijian` int(11) DEFAULT 0 NOT NULL COMMENT '评估时间',
    `yinhangdiyae` int(11) DEFAULT 0 NOT NULL COMMENT '银行抵押额',
    `yinhangshengyue` int(11) DEFAULT 0 NOT NULL COMMENT '银行剩余额',
    `jiekuane` int(11) DEFAULT 0 NOT NULL COMMENT '借款额',
    `diyalv` int(11) DEFAULT 0 NOT NULL COMMENT '抵押率[%]',
    `jiekuandaoqishijian` int(11) DEFAULT 0 NOT NULL COMMENT '借款到期时间',
    `chandiaochaxunshijian` int(11) DEFAULT 0 NOT NULL COMMENT '产调查询时间',
    `xiacichaxunshijian` int(11) DEFAULT 0 NOT NULL COMMENT '下次查询时间',
    `beizhu` varchar(255) DEFAULT '' NOT NULL COMMENT '备注',
    `createTime` int(11) DEFAULT 0 NOT NULL COMMENT '创建时间',
    `updateTime` int(11) DEFAULT 0 NOT NULL COMMENT '更新时间',
    `status` tinyint(4) DEFAULT 0 NOT NULL COMMENT '状态位',
    `iRecordVerID` int(11) NOT NULL DEFAULT 0,
    `sLockData` varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='融房产信息';

DROP TABLE IF EXISTS `fk_ronghuifangjilu`;
CREATE TABLE `fk_ronghuifangjilu` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `kehubianhao` int(11) NOT NULL DEFAULT '0' COMMENT '客户编号',
  `kehu` varchar(40) NOT NULL DEFAULT '' COMMENT '客户',
  `huifangshijian` varchar(36) DEFAULT '' COMMENT '回访时间',
  `huifangfangshi` varchar(40) DEFAULT '' COMMENT '回访方式',
  `huifangrenyuan` varchar(40) DEFAULT '' COMMENT '回访人员',
  `huifangqingkuang` varchar(255) DEFAULT '' COMMENT '回访情况',
  `iRecordVerID` int(11) NOT NULL DEFAULT '0',
  `sLockData` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='融回访记录';

CREATE TABLE `fk_touzixiangmubiao` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `touzihetongbianhao` varchar(40) NOT NULL DEFAULT '' COMMENT '投资合同编号',
  `touziren` varchar(40) NOT NULL DEFAULT '' COMMENT '投资人',
  `yinhangzhanghao` varchar(80) NOT NULL DEFAULT '' COMMENT '银行账号',
  `kaihuxingxinxi` varchar(80) NOT NULL DEFAULT '' COMMENT '开户行信息',
  `touziewanyuan` bigint(20) NOT NULL DEFAULT '0' COMMENT '投资额[万元], 单位是分',
  `qishiriqi` int(11) NOT NULL DEFAULT '0' COMMENT '起始日期',
  `yue` tinyint(4) NOT NULL DEFAULT '0' COMMENT '月',
  `tian` tinyint(4) NOT NULL DEFAULT '0' COMMENT '天',
  `daoqiriqi` int(11) NOT NULL DEFAULT '0' COMMENT '到期日期',
  `fuxiri` tinyint(2) NOT NULL DEFAULT 0 COMMENT '付息日',
  `fuxifangshi` varchar(40) NOT NULL DEFAULT '' COMMENT '付息方式',
  `yuexi` int(11) NOT NULL DEFAULT '0.0000' COMMENT '月息[%]',
  `yingfuyuan` bigint(20) NOT NULL DEFAULT '0' COMMENT '应付[元]',
  `zongeyuan` bigint(20) NOT NULL DEFAULT '0' COMMENT '总额[元]',
  `kehujingli` varchar(40) NOT NULL DEFAULT '' COMMENT '客户经理',
  `ticheng` int(11) NOT NULL DEFAULT '0.0000' COMMENT '提成[%]',
  `tichengyuan` bigint(20) NOT NULL DEFAULT '0' COMMENT '提成[元]',
  `tichengzongeyuan` bigint(20) NOT NULL DEFAULT '0' COMMENT '提成总额[元]',
  `fangkuanrenyinhang` varchar(40) NOT NULL DEFAULT '' COMMENT '放款人[银行]',
  `rongzihetongbianhao` varchar(40) NOT NULL DEFAULT '' COMMENT '融资合同编号',
  `jiekuanren` varchar(40) NOT NULL DEFAULT '' COMMENT '借款人',
  `jieqingqingkuang` tinyint(4) NOT NULL DEFAULT '0' COMMENT '结清情况',
  `beizhu` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `createTime` int(11) NOT NULL DEFAULT '0' COMMENT '记录添加时间',
  `updateTime` int(11) NOT NULL DEFAULT '0' COMMENT '记录更新时间',
  `iRecordVerID` int(11) NOT NULL DEFAULT '0',
  `sLockData` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `touzixiangmubiao_hetongbianhao` (`touzihetongbianhao`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='投资项目表';

CREATE TABLE `fk_touzidangan` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
    `touzihetongbianhao` varchar(40) DEFAULT '' NOT NULL COMMENT '投资合同编号',
    `touziren` varchar(40) DEFAULT '' NOT NULL COMMENT '投资人',
    `touziewanyuan` int(11) DEFAULT 0 NOT NULL COMMENT '投资额[万元]',
    `qishiriqi` int(11) DEFAULT 0 NOT NULL COMMENT '起始日期',
    `yue` tinyint(4) DEFAULT 0 NOT NULL COMMENT '月',
    `tian` tinyint(4) DEFAULT 0 NOT NULL COMMENT '天',
    `daoqiriqi` int(11) DEFAULT 0 NOT NULL COMMENT '到期日期',
    `fangkuanrenyinhang` int(11) DEFAULT 0 NOT NULL COMMENT '放款人[银行]',
    `rongzihetongbianhao` varchar(40) DEFAULT '' NOT NULL COMMENT '融资合同编号',
    `jiekuanren` varchar(40) DEFAULT '' NOT NULL COMMENT '借款人',
    `yuexi` int(11) DEFAULT 0 NOT NULL COMMENT '月息[%]',
    `touzihetong` tinyint(4) DEFAULT 0 NOT NULL COMMENT '投资合同',
    `haikuanmingxibiao` tinyint(4) DEFAULT 0 NOT NULL COMMENT '还款明细表',
    `zhuanzhangpingtiao` tinyint(4) DEFAULT 0 NOT NULL COMMENT '转账凭条',
    `haikuanzhuanzhangpingzheng` tinyint(4) DEFAULT 0 NOT NULL COMMENT '还款转账凭证',
    `taxiangquanzheng` tinyint(4) DEFAULT 0 NOT NULL COMMENT '他项权证',
    `beizhu` varchar(255) DEFAULT '' NOT NULL COMMENT '备注',
    `createTime` int(11) DEFAULT 0 NOT NULL COMMENT '创建时间',
    `updateTime` int(11) DEFAULT 0 NOT NULL COMMENT '更新时间',
    `status` tinyint(4) DEFAULT 0 NOT NULL COMMENT '状态位',
    `iRecordVerID` int(11) NOT NULL DEFAULT 0,
    `sLockData` varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='投资档案';

DROP TABLE IF EXISTS `fk_touzikehumingce`;
CREATE TABLE `fk_touzikehumingce` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `xingming` varchar(16) DEFAULT '' COMMENT '姓名',
  `zhengjianhaoma` varchar(18) DEFAULT '' COMMENT '证件号码',
  `lianxidianhua` varchar(11) DEFAULT '' COMMENT '联系电话',
  `yinhangzhanghao` varchar(32) DEFAULT '' COMMENT '银行账号',
  `kaihuxingxinxi` varchar(32) DEFAULT '' COMMENT '开户行信息',
  `jiatingzhuzhi` varchar(64) DEFAULT '' COMMENT '家庭住址',
  `iRecordVerID` int(11) NOT NULL DEFAULT '0',
  `sLockData` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `touzikehumingce_xingming` (`xingming`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='投资客户名册';

drop table IF EXISTS `fk_fangkuantijiangbiao`;
CREATE TABLE `fk_fangkuantijiangbiao` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `rongzihetongbianhao` varchar(40) NOT NULL DEFAULT '' COMMENT '融资合同编号',
  `jiekuanren` varchar(80) NOT NULL DEFAULT '' COMMENT '借款人',
  `fangkuanshijian` int(11) NOT NULL DEFAULT '0' COMMENT '放款时间',
  `jiekuanewanyuan` bigint(20) NOT NULL DEFAULT '0' COMMENT '借款额[万元]',
  `qixianyue` tinyint(4) NOT NULL DEFAULT '0' COMMENT '期限[月]',
  `anyuebiliyue` int(11) NOT NULL DEFAULT '0' COMMENT '按月比例[%/月]',
  `zhanqi` tinyint(4) NOT NULL DEFAULT '0' COMMENT '展期',
  `diya` tinyint(4) NOT NULL DEFAULT '0' COMMENT '抵押',
  `huanfanglei` tinyint(4) NOT NULL DEFAULT '0' COMMENT '换房类',
  `tijiangbiliyue` int(11) NOT NULL DEFAULT '0' COMMENT '提奖比例[%/月]',
  `tijiangjineyuan` bigint(20) NOT NULL DEFAULT '0' COMMENT '提奖金额[元]',
  `yuliubili` int(11) NOT NULL DEFAULT '0' COMMENT '预留比例[%]',
  `kehujingli` varchar(40) NOT NULL DEFAULT '' COMMENT '客户经理',
  `gerentijiangyuan` bigint(20) NOT NULL DEFAULT '0' COMMENT '个人提奖[元]',
  `gerenyuliuyuan` bigint(20) NOT NULL DEFAULT '0' COMMENT '个人预留[元]',
  `gerenfafangyuan` bigint(20) NOT NULL DEFAULT '0' COMMENT '个人发放[元]',
  `jinglixingming` varchar(40) NOT NULL DEFAULT '' COMMENT '经理姓名',
  `jinglitijiangbili` int(11) NOT NULL DEFAULT '0' COMMENT '经理提奖比例',
  `jinglitijiang` bigint(20) NOT NULL DEFAULT '0' COMMENT '经理提奖',
  `jingliyuliu` bigint(20) NOT NULL DEFAULT '0' COMMENT '经理预留',
  `jinglifafang` bigint(20) NOT NULL DEFAULT '0' COMMENT '经理发放',
  `zongjianxingming` varchar(40) NOT NULL DEFAULT '' COMMENT '总监姓名',
  `zongjiantijiangbili` int(11) NOT NULL DEFAULT '0' COMMENT '总监提奖比例',
  `zongjiantijiang` bigint(20) NOT NULL DEFAULT '0' COMMENT '总监提奖',
  `zongjianyuliu` int(11) NOT NULL DEFAULT '0' COMMENT '总监预留',
  `zongjianfafang` bigint(20) NOT NULL DEFAULT '0' COMMENT '总监发放',
  `fengkongjingli` varchar(40) NOT NULL DEFAULT '' COMMENT '风控经理',
  `fengkongtijiang` bigint(20) NOT NULL DEFAULT '0' COMMENT '风控提奖',
  `fangkuanren` varchar(40) NOT NULL DEFAULT '' COMMENT '放款人',
  `fangkuanrentijiang` bigint(20) NOT NULL DEFAULT '0' COMMENT '放款人提奖',
  `beizhu` varchar(255) NOT NULL DEFAULT '' COMMENT '备注',
  `createTime` int(11) NOT NULL DEFAULT '0' COMMENT '记录添加时间',
  `updateTime` int(11) NOT NULL DEFAULT '0' COMMENT '记录更新时间',
  `iRecordVerID` int(11) NOT NULL DEFAULT '0',
  `sLockData` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='放款提奖表';

CREATE TABLE `fk_yuliufanhuanzhang` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
    `rongzihetongbianhao` int(11) DEFAULT 0 NOT NULL COMMENT '融资合同编号',
    `jiekuanren` varchar(80) DEFAULT '' NOT NULL COMMENT '借款人',
    `kehujingli` varchar(40) DEFAULT '' NOT NULL COMMENT '客户经理',
    `gerenyuliu` int(11) DEFAULT 0 NOT NULL COMMENT '个人预留',
    `meiqifafang` int(11) DEFAULT 0 NOT NULL COMMENT '每期发放',
    `jinglixingming` varchar(40) DEFAULT '' NOT NULL COMMENT '经理姓名',
    `jingliyuliu` int(11) DEFAULT 0 NOT NULL COMMENT '经理预留',
    `meiqifafang258` int(11) DEFAULT 0 NOT NULL COMMENT '每期发放258',
    `zongjianxingming` varchar(40) DEFAULT '' NOT NULL COMMENT '总监姓名',
    `zongjianyuliu` int(11) DEFAULT 0 NOT NULL COMMENT '总监预留',
    `meiqifafang261` int(11) DEFAULT 0 NOT NULL COMMENT '每期发放261',
    `fangkuanshijian` int(11) DEFAULT 0 NOT NULL COMMENT '放款时间',
    `qixianyue` tinyint(4) DEFAULT 0 NOT NULL COMMENT '期限[月]',
    `yingfaqishu` tinyint(4) DEFAULT 0 NOT NULL COMMENT '应发期数',
    `yifaqishu` tinyint(4) DEFAULT 0 NOT NULL COMMENT '已发期数',
    `xiaciyingfayuefen` tinyint(4) DEFAULT 0 NOT NULL COMMENT '下次应发月份',
    `fafangzhuangtai` tinyint(4) DEFAULT 0 NOT NULL COMMENT '发放状态',
    `cunqianguanru` int(11) DEFAULT 0 NOT NULL COMMENT '存钱罐[入]',
    `beizhu` varchar(255) DEFAULT '' NOT NULL COMMENT '备注',
    `createTime` int(11) DEFAULT 0 NOT NULL COMMENT '创建时间',
    `updateTime` int(11) DEFAULT 0 NOT NULL COMMENT '更新时间',
    `status` tinyint(4) DEFAULT 0 NOT NULL COMMENT '状态位',
    `iRecordVerID` int(11) NOT NULL DEFAULT 0,
    `sLockData` varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='预留返还账';

DROP TABLE IF EXISTS `fk_dianxiaotijiangbiao`;
CREATE TABLE `fk_dianxiaotijiangbiao` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `yewubianhao` varchar(16) DEFAULT '' COMMENT '业务编号',
  `kehuxingming` varchar(16) DEFAULT '' COMMENT '客户姓名',
  `rongzijinewanyuan` int(11) DEFAULT '0' COMMENT '融资金额[万元]',
  `hezuoyinhang` varchar(16) DEFAULT '' COMMENT '合作银行',
  `yewuleixing` tinyint(4) DEFAULT '0' COMMENT '业务类型',
  `shoufeijinewanyuan` int(11) DEFAULT '0' COMMENT '收费金额[万元]',
  `shoufeiriqi` int(11) DEFAULT '0' COMMENT '收费日期',
  `jiedanren` varchar(16) DEFAULT '' COMMENT '接单人',
  `jibie` varchar(16) DEFAULT '' COMMENT '级别',
  `dangyueheji` int(11) DEFAULT '0' COMMENT '当月合计',
  `tijiangbili` varchar(16) DEFAULT '' COMMENT '提奖比例',
  `tijiangjine` varchar(32) DEFAULT '' COMMENT '提奖金额',
  `tandanren` varchar(16) DEFAULT '' COMMENT '谈单人',
  `tijiangbili284` varchar(16) DEFAULT '' COMMENT '提奖比例284',
  `tijiangjine285` varchar(32) DEFAULT '' COMMENT '提奖金额285',
  `gendanren` varchar(16) DEFAULT '' COMMENT '跟单人',
  `tijiangbili287` varchar(16) DEFAULT '' COMMENT '提奖比例287',
  `tijiangjine288` varchar(32) DEFAULT '' COMMENT '提奖金额288',
  `zuodanren` varchar(16) DEFAULT '' COMMENT '做单人',
  `tijiangbili290` varchar(16) DEFAULT '' COMMENT '提奖比例290',
  `tijiangjine291` varchar(32) DEFAULT '' COMMENT '提奖金额291',
  `bumenjingli` varchar(16) DEFAULT '' COMMENT '部门经理',
  `tijiangbili293` varchar(16) DEFAULT '' COMMENT '提奖比例293',
  `tijiangjine294` varchar(32) DEFAULT '' COMMENT '提奖金额294',
  `iRecordVerID` int(11) NOT NULL DEFAULT '0',
  `sLockData` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `dianxiaotijiangbiao_yewubianhao` (`yewubianhao`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='电销提奖表';

drop table if exists `fk_kehujinglimingce`;
CREATE TABLE `fk_kehujinglimingce` (
    `id` int(11) not null auto_increment comment '自增id',
    `xingming` varchar(40) DEFAULT '' NOT NULL COMMENT '姓名',
    `jibie` tinyint(4) DEFAULT 0 NOT NULL COMMENT '级别 0 专员, 1经理, 2 总监',
    `shangjijingli` varchar(40) DEFAULT '' NOT NULL COMMENT '上级经理',
    `shangjizongjian` varchar(40) DEFAULT '' NOT NULL COMMENT '上级总监',
    `zaizhiqingkuang` tinyint(4) DEFAULT 0 NOT NULL COMMENT '在职情况 0 否, 1 是',
    `createTime` int(11) not null default 0 comment '记录添加时间',
    `updateTime` int(11) not null default 0 comment '记录更新时间',
    `iRecordVerID` int(11) NOT NULL DEFAULT '0',
    `sLockData` varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY  (`id`),
    UNIQUE KEY `kehujinglimingce_xingming`(`xingming`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='客户经理名册';

drop table if exists `fk_fengkongjinglimingce`;
CREATE TABLE `fk_fengkongjinglimingce` (
    `id` int(11) not null AUTO_INCREMENT comment 'id',
    `xingming` varchar(40) DEFAULT '' NOT NULL COMMENT '姓名',
    `jibie` varchar(40) DEFAULT '' NOT NULL COMMENT '级别',
    `ruzhishijian` int(11) DEFAULT 0 NOT NULL COMMENT '入职时间',
    `zaizhiqingkuang` tinyint(4) DEFAULT 0 NOT NULL COMMENT '在职情况',
    `createTime` int(11) not null default 0 comment '记录添加时间',
    `updateTime` int(11) not null default 0 comment '记录更新时间',
    `iRecordVerID` int(11) NOT NULL DEFAULT '0',
    `sLockData` varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`),
    UNIQUE KEY `fengkongjinglimingce_xingming` (`xingming`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='风控经理名册';

drop table if exists `fk_fangkuanrenmingce`;
CREATE TABLE `fk_fangkuanrenmingce` (
    `id` int(11) not null auto_increment comment '自增id',
    `fangkuanren` varchar(40) DEFAULT '' NOT NULL COMMENT '放款人',
    `fangkuanrenyinhang` varchar(40) DEFAULT '' NOT NULL COMMENT '放款人[银行]',
    `yinhangzhanghao` varchar(255) DEFAULT '' NOT NULL COMMENT '银行账号',
    `kaihuxingxinxi` varchar(40) DEFAULT '' NOT NULL COMMENT '开户行信息',
    `xianshangnicheng` varchar(40) DEFAULT '' NOT NULL COMMENT '线上昵称',
    `createTime` int(11) not null default 0 comment '记录添加时间',
    `updateTime` int(11) not null default 0 comment '记录更新时间',
    `iRecordVerID` int(11) NOT NULL DEFAULT '0',
    `sLockData` varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`),
    UNIQUE KEY `fangkuanrenmingce_yinhang` (`fangkuanrenyinhang`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='放款人名册';

CREATE TABLE `fk_xianshangxiangmubiao` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
    `shangbiaoriqi` int(11) DEFAULT 0 NOT NULL COMMENT '上标日期',
    `biaodimingcheng` varchar(40) DEFAULT '' NOT NULL COMMENT '标的名称',
    `jiekuanren` int(11) DEFAULT 0 NOT NULL COMMENT '借款人',
    `nicheng` varchar(40) DEFAULT '' NOT NULL COMMENT '昵称',
    `fangkuanriqi` int(11) DEFAULT 0 NOT NULL COMMENT '放款日期',
    `biaodijineyuan` int(11) DEFAULT 0 NOT NULL COMMENT '标的金额[分]',
    `nianlilv` int(11) DEFAULT 0 NOT NULL COMMENT '年利率[%]',
    `yue` varchar(40) DEFAULT '' NOT NULL COMMENT '月',
    `tian` varchar(40) DEFAULT '' NOT NULL COMMENT '天',
    `hao` varchar(40) DEFAULT '' NOT NULL COMMENT '号',
    `fuwufei` int(11) DEFAULT 0 NOT NULL COMMENT '服务费[%]',
    `fuwufeiyuan` int(11) DEFAULT 0 NOT NULL COMMENT '服务费[分]',
    `shouquriqi` int(11) DEFAULT 0 NOT NULL COMMENT '收取日期',
    `shijidaozhangyuan` int(11) DEFAULT 0 NOT NULL COMMENT '实际到账[分]',
    `toubiaojineyuan` int(11) DEFAULT 0 NOT NULL COMMENT '投标金额[分]',
    `kehutoubiaojineyuan` int(11) DEFAULT 0 NOT NULL COMMENT '客户投标金额[分]',
    `daoqiriqi` int(11) DEFAULT 0 NOT NULL COMMENT '到期日期',
    `jieqingqingkuang` tinyint(4) DEFAULT 0 NOT NULL COMMENT '结清情况',
    `beizhu` varchar(255) DEFAULT '' NOT NULL COMMENT '备注',
    `createTime` int(11) DEFAULT 0 NOT NULL COMMENT '创建时间',
    `updateTime` int(11) DEFAULT 0 NOT NULL COMMENT '更新时间',
    `status` tinyint(4) DEFAULT 0 NOT NULL COMMENT '状态位',
    `iRecordVerID` int(11) NOT NULL DEFAULT 0,
    `sLockData` varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='线上项目表';

CREATE TABLE `fk_xianshangbenxifeizhang` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
    `biaodimingcheng` int(11) DEFAULT 0 NOT NULL COMMENT '标的名称',
    `jiekuanren` varchar(40) DEFAULT '' NOT NULL COMMENT '借款人',
    `qishu` int(11) DEFAULT 0 NOT NULL COMMENT '期数',
    `zhifushijian` int(11) DEFAULT 0 NOT NULL COMMENT '支付时间',
    `lixiyuan` int(11) DEFAULT 0 NOT NULL COMMENT '利息[分]',
    `feiyongyuanguanlifei` int(11) DEFAULT 0 NOT NULL COMMENT '费用[分]_管理费',
    `feiyongyuanzhongjiefei` int(11) DEFAULT 0 NOT NULL COMMENT '费用[分]_中介费',
    `feiyongyuanfuwufei` int(11) DEFAULT 0 NOT NULL COMMENT '费用[分]_服务费',
    `feiyongyuanqita` int(11) DEFAULT 0 NOT NULL COMMENT '费用[分]_其他',
    `hejiyuan` int(11) DEFAULT 0 NOT NULL COMMENT '合计[元]',
    `haikuanqingkuang` tinyint(4) DEFAULT 0 NOT NULL COMMENT '还款情况',
    `beizhu` varchar(255) DEFAULT '' NOT NULL COMMENT '备注',
    `createTime` int(11) DEFAULT 0 NOT NULL COMMENT '创建时间',
    `updateTime` int(11) DEFAULT 0 NOT NULL COMMENT '更新时间',
    `status` tinyint(4) DEFAULT 0 NOT NULL COMMENT '状态位',
    `iRecordVerID` int(11) NOT NULL DEFAULT 0,
    `sLockData` varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='线上本息费账';

CREATE TABLE `fk_xianshangrijizhang` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
    `zhonglei` tinyint(4) DEFAULT 0 NOT NULL COMMENT '种类',
    `zhanghao` int(11) DEFAULT 0 NOT NULL COMMENT '账号',
    `riqi` int(11) DEFAULT 0 NOT NULL COMMENT '日期',
    `qichuyueyuan` int(11) DEFAULT 0 NOT NULL COMMENT '期初余额[分]',
    `cunqianguanru` int(11) DEFAULT 0 NOT NULL COMMENT '存钱罐[入]',
    `xianxiachongzhiru` int(11) DEFAULT 0 NOT NULL COMMENT '线下充值[入]',
    `qiyehuchongzhiru` int(11) DEFAULT 0 NOT NULL COMMENT '企业户充值[入]',
    `haoyoufanxianru` int(11) DEFAULT 0 NOT NULL COMMENT '好友返现[入]',
    `shoudaofangkuaneru` int(11) DEFAULT 0 NOT NULL COMMENT '收到放款额[入]',
    `daoqibenjinru` int(11) DEFAULT 0 NOT NULL COMMENT '到期本金[入]',
    `daoqilixiru` int(11) DEFAULT 0 NOT NULL COMMENT '到期利息[入]',
    `diaopeizijinru` int(11) DEFAULT 0 NOT NULL COMMENT '调配资金[入]',
    `jiedongzijinru` int(11) DEFAULT 0 NOT NULL COMMENT '解冻资金[入]',
    `tixianchu` int(11) DEFAULT 0 NOT NULL COMMENT '提现[出]',
    `shouxufeichu` int(11) DEFAULT 0 NOT NULL COMMENT '手续费[出]',
    `zhuanzhangzijinchu` int(11) DEFAULT 0 NOT NULL COMMENT '转账资金[出]',
    `dongjiezijinchu` int(11) DEFAULT 0 NOT NULL COMMENT '冻结资金[出]',
    `zhifubenxichu` int(11) DEFAULT 0 NOT NULL COMMENT '支付本息[出]',
    `zhifutoubiaochu` int(11) DEFAULT 0 NOT NULL COMMENT '支付投标[出]',
    `qimoyueyuan` int(11) DEFAULT 0 NOT NULL COMMENT '期末余额[分]',
    `beizhu` varchar(255) DEFAULT '' NOT NULL COMMENT '备注',
    `createTime` int(11) DEFAULT 0 NOT NULL COMMENT '创建时间',
    `updateTime` int(11) DEFAULT 0 NOT NULL COMMENT '更新时间',
    `status` tinyint(4) DEFAULT 0 NOT NULL COMMENT '状态位',
    `iRecordVerID` int(11) NOT NULL DEFAULT 0,
    `sLockData` varchar(255) NOT NULL DEFAULT '',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='线上日记账';
