<div id="lajibuju" style="height: 100%;overflow: auto">
<ul class="nav nav-tabs" role="tablist" style="margin:0;">
    <li class="active"><a href="#write-tab" role="tab" data-toggle="tab"> 书写日志 </a></li>
    <?php
    $hisParmas = [];
    switch ($this->targetTab) {
        case 'list':
            $hisParmas = $this->jumpParams;
            break;
        default:
            break;
    }
    ?>
    <li><a href="<?php echo \Sooh\Base\Tools::uri($hisParmas, 'tabhistorylog'); ?>" role="tab" data-toggle="ajaxtab"
           data-target="#list-tab" data-reload="false"> 查看历史日志 </a></li>
    <li><a href="<?php echo \Sooh\Base\Tools::uri([], 'tabreportlog'); ?>" role="tab" data-toggle="ajaxtab"
           data-target="#report-tab" data-reload="false"> 生成报表 </a></li>
</ul>
<div class="tab-content">
    <div class="tab-pane fade active in" id="write-tab">
        <form id="pagerForm" data-toggle="ajaxsearch" method="post" action="<?php echo \Sooh\Base\Tools::uri(); ?>">
            <label for="">日期</label>
            <input type="text" data-toggle="datepicker" name="date" size="14" value="<?php echo $date; ?>"/>
            <button type="submit" class="btn btn-default">查询</button>
        </form>
        <div class="bjui-pageContent">
            <?php echo $view; ?>
        </div>
    </div>
    <div class="tab-pane fade" id="list-tab">

    </div>
    <div class="tab-pane fade" id="report-tab">

    </div>
</div>
<script>
    $('[data-target="#<?php echo $this->targetTab; ?>-tab"]').click();
</script>
</div>
