<?php echo $this->renderInc('head4login');?>
<br/><br/><br/>
<div class="col-sm-4"></div>
<div class="col-sm-4">
	<div class="panel panel-primary">
	<div class="panel-heading">
	  <h3 class="panel-title"><img border="0" src="/images/logo-small.png"></h3>
	</div>
	<div class="panel-body">


	  <div class="form-group">
		<label for="exampleInputEmail1">账户名</label>
		<input type="text" class="form-control" id="uu" placeholder="请输入帐号" value="<?php echo $_COOKIE["last_login_name"];?>">
	  </div>
	  <div class="form-group">
		<label for="exampleInputPassword1">密码</label>
		<input type="password" class="form-control" id="pp" placeholder="请输入密码">
	  </div>

	  <table border=0 width=100%><tr><td>
				  <input type="checkbox" id="remember" name="remember" value=1 <?php if(!empty($_COOKIE["last_login_name"]))echo "checked"?>> <label for="remember">记住我</label>
	  </td><td>
	  <select name="clientType" id="clientType" >
		  <option value='wap' <?php if($_COOKIE['last_login_view']==='wap')echo 'selected';?> >手机版</option>
		  <option value='www' <?php if($_COOKIE['last_login_view']==='www')echo 'selected';?> >PC版</option>
		  
	  </select>
	  </td><td>
	  <button type="submit" class="btn btn-primary" onclick="replaced_submit()">登入</button>
	  </td></tr></table>



	</div>
	</div>
</div>
<div class="col-sm-4"></div>
<script type="text/javascript" src="/spread/js/device-1.min.js"></script>
<script>
$(window).load(function() {
	if (device.ios() || device.android()) {
		
	}else{
		$("select[name=clientType] option[value='www']").attr("selected", true);
	}
});

$(document).keydown(function (event) {
    if (event.keyCode == 13) {
		var args ={
			u:$('#uu').val(),
			p:$('#pp').val(),
		}
		if(undefined==args.u || args.u.length==0){
			return true;
		}else{
			if(undefined==args.p || args.p.length==0){
				return true;
			}else{
				replaced_submit();
				return false;
			}
		}
	};
    return true;
});
function replaced_submit()
{
	var args ={
		u:$('#uu').val(),
		p:$('#pp').val(),
		remember:$('#remember').val(),
		viewType:$('#clientType').val()
	}
	if(undefined==args.u || args.u.length==0){
		alert('请输入用户名');
	}else{
		if(undefined==args.p || args.p.length==0){
			alert('请输入密码');
		}
	}
	$.getJSON(urlJsonp('manage/manager/login',args,'api'),
                function (json) {
					if(json.statusCode==200){
						if($('#clientType').val()=='www'){
							top.location.href="/manage/manager/index?__VIEW__=html";
						}else{
							top.location.href="/manage/manager/welcome?__VIEW__=wap";
						}
					}else{
						if(json.message=='password failed'){
							alert('密码错误');
						}else{
							alert(json.message);
						}
					}
                }
        );
	return false;
}

</script>
<?php echo $this->renderInc('foot');?>