<?php 
$this->htmlHeadPart('<title>Hello World</title>');
$this->htmlHeadPart(\Sooh\HTML\Base::includeJS('jquery'));
echo $this->renderInc('head');
?>
<body>
	<div id="main1" style="width:660px;height:400px;border:1px solid red"></div>
	<div id="main2" style="width:660px;height:400px;border:1px solid red"></div>
	<div id="main3" style="width:660px;height:400px;border:1px solid red"></div>
	<div id="main4" style="width:660px;height:400px;border:1px solid red"></div>
	<div id="main5" style="width:660px;height:400px;border:1px solid red"></div>
	<?php
echo \Sooh\HTML\Base::includeJS('echarts-all.js');
echo \Sooh\HTML\Chart::jsFunc();
echo \Sooh\HTML\Chart::ajax('main1', 'pieSimple', "/test/index/rpt");
echo \Sooh\HTML\Chart::ajax('main2', 'barsSimple', "/test/index/rpt");
echo \Sooh\HTML\Chart::ajax('main3', 'barSimple', "/test/index/rpt");
echo \Sooh\HTML\Chart::ajax('main4', 'lineSimple', "/test/index/rpt");
echo \Sooh\HTML\Chart::ajax('main5', 'linesSimple', "/test/index/rpt");
echo $this->renderInc('foot');