<?php
echo $this->renderInc('head');
echo $this->renderInc('wapmenu');
?>
    <div class="container">

        <fieldset style="">
            <ul>
                <li style="padding-bottom: 15px;"><a href="/report/pcsitetraffic/index?__VIEW__=wap">网页流量</a></li>
                <li style="padding-bottom: 15px;"><a href="/report/umengdata/index?__VIEW__=wap">App流量</a></li>
                <li style="padding-bottom: 15px;"><a href="/report/regtoinvestmenttrans/index?__VIEW__=wap">注册至理财人数</a></li>
                <li style="padding-bottom: 15px;"><a href="/report/regtoinvestmenttransrate/index?__VIEW__=wap">注册至理财转化率</a></li>
                <li style="padding-bottom: 15px;"><a href="/report/newfinancial/index?__VIEW__=wap">新增理财人数</a></li>
               <li style="padding-bottom: 15px;"><a href="/report/newlicaiamount/index?__VIEW__=wap">新增理财金额</a></li>
               <li style="padding-bottom: 15px;"><a href="/report/newfinancialavg/index?__VIEW__=wap">新增理财人均</a></li>
               <li style="padding-bottom: 15px;"><a href="/report/oldandnewfinancial/index?__VIEW__=wap">新老用户理财人数</a></li>
               <li style="padding-bottom: 15px;"><a href="/report/oldandnewfinancialamount/index?__VIEW__=wap">新老用户理财金额</a></li>
               <li style="padding-bottom: 15px;"><a href="/report/oldandnewfinancialavg/index?__VIEW__=wap">新老用户理财人均</a></li>
               <li style="padding-bottom: 15px;"><a href="/report/fundsdata/index?__VIEW__=wap">资金情况</a></li>
               <li style="padding-bottom: 15px;"><a href="/report/retaineddata/index?__VIEW__=wap">留存情况</a></li>
               <li style="padding-bottom: 15px;"><a href="/report/compounddata/index?__VIEW__=wap">复投人数</a></li>
               <li style="padding-bottom: 15px;"><a href="/report/compoundrate/index?__VIEW__=wap">复投率</a></li>
            </ul>
    </fieldset>
</div>

<?php echo $this->renderInc('foot');?>
