<?php
	$args=$this->args;
	//$rs = $this->records;
	echo "TODO: 等新的日志系统";
	$display =$this->grpName;
	$chartid=1;

//	echo '<div id="main'.$chartid.'"  class="divChartDefault"></div>';
//	$args['forGrp']='';
//	$args['forAct']='Register';
//	$args['title']='7日注册走势';
//	$args['subtitle']='（总数）';
//	echo \Sooh\HTML\Chart::ajax('main'.$chartid, 'lineSimple', \Sooh\Base\Tools::uri($args, 'weekfor'));
//	$chartid++;
//	
//	echo '<div id="main'.$chartid.'"  class="divChartDefault"></div>';
//	$args['forGrp']='clienttype';
//	$args['forAct']='Register';
//	$args['title']='7日注册走势';
//	$args['subtitle']='（按客户端区分）';
//	echo \Sooh\HTML\Chart::ajax('main'.$chartid, 'linesSimple', \Sooh\Base\Tools::uri($args, 'weekfor'));
//	$chartid++;

