<?php
	
	$args=$this->args;//array('forAct'=>$forAct,'ymd'=>$ymd)
	$display =$this->grpName;
	$display['flgext01']='按产品类型统计';
	$chartid=1;
	
	$md = $this->args['ymd']%10000;
	$md = floor($md/100).'-'.($md%100);
	$prdtTypes = json_encode(\PrjLib\Config::fetch('enum_prdtType'));
	
	echo '<div id="main'.$chartid.'"  class="divChartDefault"></div>';
	$args['forGrp']='';
	$args['useActAsGrp']='NewerBought,LaterBought,RegAndBought';
	$args['grpNameFix']='老用户,新注册用户';
	$args['title']='7日购买人数走势';
	$args['subtitle']='（总额）';
	echo \Sooh\HTML\Chart::ajax('main'.$chartid, 'linesSimple', \Sooh\Base\Tools::uri($args, 'weekfor'));
	$chartid++;
	unset($args['useActAsGrp'],$args['grpNameFix']);
	
	echo '<div id="main'.$chartid.'"  class="divChartDefault"></div>';
	$args['forGrp']='';
	$args['useActAsGrp']='Register,RegAndBindOk,RegAndBought';
	$args['grpNameFix']='新注册用户,新绑卡用户,新购买用户';
	$args['title']='7日总购买走势';
	$args['subtitle']='（总额）';
	echo \Sooh\HTML\Chart::ajax('main'.$chartid, 'barsSimple', \Sooh\Base\Tools::uri($args, 'weekfor'));
	$chartid++;
	unset($args['useActAsGrp'],$args['grpNameFix']);
	
	echo '<div id="main'.$chartid.'"  class="divChartDefault"></div>';
	$args['forGrp']='flgext01';	$args['extFlgNames']= $prdtTypes;
	$args['forAct']='BoughtEachTotal';
	$args['title']='购买各类产品人数分布';
	$args['subtitle']=$md.' ';
	echo \Sooh\HTML\Chart::ajax('main'.$chartid, 'pieSimple', \Sooh\Base\Tools::uri($args, 'onedayfor'));
	$chartid++;
	unset($args['useActAsGrp'],$args['grpNameFix'],$args['extFlgNames']);
	
	echo '<div id="main'.$chartid.'"  class="divChartDefault"></div>';
	$args['forGrp']='flgext01';	$args['extFlgNames']= $prdtTypes;
	$args['forAct']='LaterBoughtEach,RegAndBoughtEach';
	$args['grpNameFix']='老用户购买{}人数,新用户购买{}人数';
	$args['title']='购买各类产品人数分布';
	$args['subtitle']=$md.'（区分新注册和老用户）';
	echo \Sooh\HTML\Chart::ajax('main'.$chartid, 'pieSimple', \Sooh\Base\Tools::uri($args, 'onedayfor'));
	$chartid++;
	unset($args['useActAsGrp'],$args['grpNameFix'],$args['extFlgNames']);	
	
	
	
	
