<?php 
// $this->htmlHeadPart('<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=0.5, maximum-scale=2.0, user-scalable=yes" /> ');
// $this->htmlHeadPart('<title>最近日统计（当天是每小时更新）</title>');
// $this->htmlHeadPart(\Sooh\HTML\Base::includeJS('jquery'));
// $this->htmlHeadPart(\Sooh\HTML\Base::includeJS('jquery.form.min.js'));
// echo $this->renderInc('head');
?>
<!-- <body> -->
<div class="bjui-pageContent">
<?php 
//		echo '说明：增长0~10%<font style="color:red;font-weight:bold">↑</font>，增长10~30%<font style="color:red;font-weight:bold">↑↑</font>，
//	增长30%以上<font style="color:red;font-weight:bold">↑↑↑</font><br/>';
$actName = $this->actName;
$prdtbuy = $this->prdtbuy;
$weekdayName=$this->weekdayName;
$copartners = $this->copartners;
//$names =$this->actName;
//$names['LoginPc'] = 'PC端活跃用户';
//$names['LoginMobile'] = '移动端活跃用户';
$rs = $this->records;
$lst=$this->rptGroupDefine;

$ymds = array_keys($rs);
$nYmd = sizeof($ymds);
for($i=0;$i<$nYmd;$i++){
	$ymd = $ymds[$i];
	$r = $rs[$ymd];
	$s = "<div><table  style='width: 400px; float:left;' class=\"table-bordered table table-hover\"><thead><tr><th>日期<th>".date("Y年m月d日",  strtotime($ymd))."<th>周".$weekdayName[date('w',strtotime($ymd))]."</th></tr></thead>";
	
	foreach($lst as $listId=>$row){
		if ($ymd == date('Ymd') && ($listId == 'p_yebfundflows' || $listId == 'p_dybfundflows')) {
			continue;
		}

		$tr = "<tr><td>{$row['fmt'][0]}<td>";
        if(!empty($row['extraRate'])){
            foreach($row['extraRate'] as $rateName=>$define){
                if($r[$define[1]]>0){
                    $r[$rateName] = sprintf("%.1f",($r[$define[0]]/$r[$define[1]]*100));
                }else{
                    $r[$rateName] = 0;
                }
            }
        }
		$url = \Sooh\Base\Tools::uri(['forAct'=>$listId,'ymd'=>$ymd,"__VIEW__"=>\Sooh\Base\Ini::getInstance()->viewRenderType()],'depth1');
		if ($r['{ApplyWithdrawAmount}'] > $r['{ChargeAmount}']) {
			$r['{ApplyWithdrawAmount}'] = '<span style="color:red">'.$r['{ApplyWithdrawAmount}'].'</span>';
		}
		$tr.=str_replace(array_keys($r), $r, $row['fmt'][1]);
		if(strpos($tr,'todo')){
			$s .=$tr."</td><td></td></tr>";
		}else{
			$s .=$tr."</td><td>".\Prj\Misc\View::btnDefaultInDatagrid('更多',$url,'', 'data-height="800"')."</td></tr>";
		}
		
	}
	$s.="</table>";
	$tmp = explode('@',\Sooh\Base\Session\Data::getInstance()->get('managerId'));
	if($tmp[0]==='wangzheng'){
		if (!empty($maxOrMin[$ymd])) {
			$t = '<table class="table-bordered table table-hover" style="width: 400px;float:left;">';
			foreach($maxOrMin[$ymd] as $k => $v) {
				$tbody = array($actName[$k], $copartners[$v['copartnerId']]['copartnerName'],$v['sum']);
				$t .= '<tr><td>'.implode("</td><td>", $tbody).'</td></tr>';
			}
			$t .= '</table>';
			$s.= $t;
		}
	}
	echo $s."</div><br>\n";
	echo '<div style="clear:both"></div>';

	$s = "<div><table  style='width: 400px; float:left;' class=\"table-bordered table table-hover\"><thead><tr><th>&nbsp;<th>新标<th>旧标</th></tr></thead>";
	$s .= "<tbody>";
	$s .= "<tr><td>之前买</td><td></td><td>"
			."超级用户买：".$prdtbuy[$ymd]['oldPrdtSuperBuyAmountBefore']."<br />非超级用户买：".$prdtbuy[$ymd]['oldPrdtCommonBuyAmountBefore']."<br/>使用券金额:".$prdtbuy[$ymd]['oldPrdtVoucherUseAmountBefore']."</td></tr>";
	$s .= "<tr><td>当日买</td><td>"."超级用户买：".$prdtbuy[$ymd]['newPrdtSuperBuyAmountThisDay']."<br />非超级用户买：".$prdtbuy[$ymd]['newPrdtCommonBuyAmountThisDay']."<br/>使用券金额:".$prdtbuy[$ymd]['newPrdtVoucherUseAmountThisDay']."</td><td>"
			."超级用户买：".$prdtbuy[$ymd]['oldPrdtSuperBuyAmountThisDay']."<br />非超级用户买：".$prdtbuy[$ymd]['oldPrdtCommonBuyAmountThisDay']."<br/>使用券金额:".$prdtbuy[$ymd]['oldPrdtVoucherUseAmountThisDay']."</td></tr>";
	$s .= "<tr><td>"."剩余"."</td><td>".$prdtbuy[$ymd]['newPrdtAmountLeft']."</td><td>".$prdtbuy[$ymd]['oldPrdtAmountLeft']."</td></tr>";
	$s .= "<tr><td>"."总额"."</td><td>".$prdtbuy[$ymd]['prdtAmountNew']."</td><td>".$prdtbuy[$ymd]['prdtAmountOlder']."</td></tr>";
	echo $s."</tbody></table></div><br />\n";
	echo '<div style="clear:both"></div>';
	echo "<br /><br /><br />";
}
?>
</div>

