<?php
$auths = $this->auths;
$apis = [];
try {
	$dir = realpath(__DIR__.'/../../controllers');
	$dh = opendir($dir);
	foreach ($auths as $value) {
		$className = substr($value, 0, strpos($value, '/')) . 'Controller';
		if (class_exists($className)) {
			$ref           = new \ReflectionClass($className);
			$publicMethods = $ref->getMethods(\ReflectionMethod::IS_PUBLIC);
			foreach ($publicMethods as $method) {
				$actionName    = substr($method->name, 0, -6);
				$interfaceName = substr($className, 0, -10) . "/{$actionName}";
				if (in_array($interfaceName, $auths)) {
					$methodDoc = $method->getDocComment();
					if (preg_match('/\/\*\*.*?\n\s*\*\s+?(\S+)\s*\n/i', $methodDoc, $match)) $methodDesc = $match[1];

					preg_match_all('/@param\s*(.+)\s*\n/i', $methodDoc, $match);
					$methodParamsDoc = parseMethodParameterDoc($match[1]);

					preg_match_all('/@input\s*(.+)\s*\n/i', $methodDoc, $match);
					$methodInputDoc = parseMethodParameterDoc($match[1]);

					preg_match_all('/@output\s*(.+)\s*\n/i', $methodDoc, $match);
					$methodOutputDoc = parseMethodOutputDoc($match[1]);

					$apis[$className][$actionName] = ['desc' => $methodDesc, 'params' => $methodParamsDoc, 'inputs' => $methodInputDoc, 'output' => $methodOutputDoc];
				}
			}
		}
	}

//var_dump($apis['OauthController']['authrize']);
} catch (\UnexpectedValueException $ex) {
	die('faile');
	unset($apis[$value]);
}
closedir($dh);

function parseMethodParameterDoc($doc) {
	$methodParamsDoc = array();
	foreach ($doc as $value) {
		$info = preg_split("/\s+/", trim($value));
		if (isset($info[1]) && isset($info[2])) {
			$methodParamsDoc[trim($info[1], '$')] = array('desc' => $info[2]);
			if (isset($info[0]) && trim($info[0])) {
				$methodParamsDoc[trim($info[1], '$')]['type'] = $info[0];
			}
		}
	}
	return $methodParamsDoc;
}

function parseMethodOutputDoc($doc) {
	$output = json_decode($doc[0], true);
	if ($output) {
		return $output;
	} else {
		return $doc[0];
	}
}
?>
<!DOCTYPE html>
<html ng-app="apiTest">
<head>
	<title>接口调试工具</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- 新 Bootstrap 核心 CSS 文件 -->
	<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.0/css/bootstrap.min.css">
	<link href="http://cdn.bootcss.com/prettify/r298/prettify.min.css" rel="stylesheet">
	<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
	<script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js"></script>
	<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
	<script src="http://cdn.bootcss.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<script src="http://cdn.bootcss.com/prettify/r298/prettify.min.js"></script>
	<script src="http://cdn.bootcss.com/jquery.form/3.51/jquery.form.min.js"></script>
	<script src="http://cdn.bootcss.com/angular.js/1.3.8/angular.min.js"></script>

	<script type="text/javascript">
//		document.cookie = "SoohSessId=92015a6002ce021a95c950d577d4d8c1";
		var apis = <?php echo json_encode($apis); ?>;
		var uriBase = <?php echo "'{$this->uriBase}'"; ?>;
		var doRequestUrl = uriBase + '/index.php?__=dev/testInterface&__VIEW__=json';
		angular.module("apiTest", [], function ($httpProvider) {
			$httpProvider.defaults.useXDomain = true;
			$httpProvider.defaults.headers.common["X-Requested-With"] = "XMLHttpRequest";
			$httpProvider.defaults.headers.post['Content-Type'] = 'application/x-www-form-urlencoded;charset=utf-8';

			// Override $http service's default transformRequest
			$httpProvider.defaults.transformRequest = function (data) {
				return angular.isObject(data) && String(data) !== '[object File]' ? jQuery.param(data) : data;
			};
		})
			.controller("MainController", function ($scope, $http) {
				$scope.apis = apis;
				$scope.initInputs = function () {
					$scope.request.params = {};
					$.each($scope.apis[$scope.request.module][$scope.request.api]['inputs'], function (k, v) {
						$scope.request.params[k] = v.value;
					})
				}
				$scope.doRequest = function () {
					$http.post(doRequestUrl, $scope.request).success(function (response) {
						response.params = JSON.stringify(response.params, null, 4);
						response.data = JSON.stringify(JSON.parse(response.data), null, 4);
						$scope.response = response;

					});
				}
			});
	</script>
</head>
<body>
<header class="navbar navbar-static-top navbar-default"  role="navigation">
	<div class="container">
		<div class="navbar-header">
			<button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="/test.php" class="navbar-brand">ApiTester</a>
		</div>
	</div>
</header>
<div class="container" ng-controller="MainController">
	<h1>Api接口调试工具</h1>
	<hr />
	<div class="alert alert-info" role="alert">
		<p><strong>使用说明：</strong></p>
		<p>（1）选择合适的接口。</p>
		<p>（2）系统会生成该接口的参数表，您可以直接在文本框内填入对应的参数值。</p>
		<p>（3）点击检查问题按钮，即可得到相应的调试信息。</p>
	</div>
	<div ng-show="apis" class="well ">
		<form id="form" class="form-horizontal" ng-submit='doRequest()' method="post" role="form" >
			<div class="form-group">
				<label class="col-sm-2 control-label">接口模块</label>
				<div class="col-sm-10">
					<select ng-model="request.module" class="form-control" ng-options="key as key for (key,value) in apis">
						<option value="">-- 请选择 --</option>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">接口列表</label>
				<div class="col-sm-10">
					<select ng-model="request.api" class="form-control" ng-options="key as (key+'('+value.desc+')') for (key,value) in apis[request.module]" ng-change='initParams()' >
						<option value="">-- 请选择 --</option>
					</select>
				</div>
			</div>
			<div ng-show='apis[request.module][request.api]["inputs"]' class="form-group">
				<label class="col-sm-2 control-label">参数列表</label>
				<div class="col-sm-10">

				</div>
			</div>
			<div class="form-group" ng-repeat='(key,param) in apis[request.module][request.api]["inputs"]'>
				<label class="col-sm-2 control-label">{{key}}</label>
				<div class="col-sm-3">
					<input type="text" class="form-control" ng-model="request.params[key]" >
				</div>
				<div class="col-sm-7">
					<span class="help-block">{{param.desc}}</span>
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<button type="submit" class="btn btn-success" >检查问题</button>
				</div>
			</div>
		</form>
	</div>
	<div ng-show='response' class='alert alert-info'>
		<div class="form-horizontal">
			<div class="form-group">
				<label class="col-sm-2 control-label">请求地址:</label>
				<div class="col-sm-10">
					<p class="form-control-static">{{response.url}}</p>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">请求参数:</label>
				<div class="col-sm-10">
					<pre class="form-control-static">{{response.params}}</pre>
				</div>
			</div>
			<div class="form-group">
				<label class="col-sm-2 control-label">返回结果:</label>
				<div class="col-sm-10">
					<pre class="form-control-static">{{response.data}}</pre>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
<footer class="footer ">
	<div class="container">
		<div class="center-block">
			<p class="text-muted">© 2015 喵叽理财</p>
		</div>
	</div>
</footer>

</body>
</html>
