//This file is generated by dic2comm. Don't mofity it.
import Foundation
import UIKit

class CommSender
{
	//登录
	static func login(
		_ u : String	//手机号
		, p : String	//密码
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "manage/manager/login" );
		CommCtrl.send( url
			, param : ["u":u,"p":p]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//获取菜单
	static func getMenu(
		_ callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "manage/manager/index" );
		CommCtrl.send( url
			, param : [:]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//网页流量
	static func webTraffic(
		_ ymdFrom : String	//开始日期
		, ymdTo : String	//结束日期
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "report/pcsitetraffic/index" );
		CommCtrl.send( url
			, param : ["ymdFrom":ymdFrom,"ymdTo":ymdTo]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//App流量
	static func appTraffic(
		_ ymdFrom : String	//开始日期
		, ymdTo : String	//结束日期
		, select : String?	//渠道名
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "report/umengdata/index" );
		CommCtrl.send( url
			, param : ["ymdFrom":ymdFrom,"ymdTo":ymdTo,"select":nil==select ? "":select!]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//注册至理财人数
	static func registToInvestNumbers(
		_ ymdFrom : String	//开始日期
		, ymdTo : String	//结束日期
		, selectedContractId : String?	//渠道名
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "report/regtoinvestmenttrans/index" );
		CommCtrl.send( url
			, param : ["ymdFrom":ymdFrom,"ymdTo":ymdTo,"selectedContractId":nil==selectedContractId ? "":selectedContractId!]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//注册至理财转化率
	static func registToInvestConversionRatio(
		_ ymdFrom : String	//开始日期
		, ymdTo : String	//结束日期
		, selectedContractId : String?	//渠道名
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "report/regtoinvestmenttransrate/index" );
		CommCtrl.send( url
			, param : ["ymdFrom":ymdFrom,"ymdTo":ymdTo,"selectedContractId":nil==selectedContractId ? "":selectedContractId!]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//新增理财人数
	static func newInvestNumbers(
		_ ymdFrom : String	//开始日期
		, ymdTo : String	//结束日期
		, select : String?	//渠道名
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "report/newfinancial/index" );
		CommCtrl.send( url
			, param : ["ymdFrom":ymdFrom,"ymdTo":ymdTo,"select":nil==select ? "":select!]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//新增理财金额
	static func newInvestMoney(
		_ ymdFrom : String	//开始日期
		, ymdTo : String	//结束日期
		, selectedContractId : String?	//渠道名
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "report/newlicaiamount/index" );
		CommCtrl.send( url
			, param : ["ymdFrom":ymdFrom,"ymdTo":ymdTo,"selectedContractId":nil==selectedContractId ? "":selectedContractId!]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//新增理财人均
	static func newInvestMoneyPerCapita(
		_ ymdFrom : String	//开始日期
		, ymdTo : String	//结束日期
		, select : String?	//渠道名
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "report/newfinancialavg/index" );
		CommCtrl.send( url
			, param : ["ymdFrom":ymdFrom,"ymdTo":ymdTo,"select":nil==select ? "":select!]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//新老用户理财人数
	static func newOldInvestNumbers(
		_ ymdFrom : String	//开始日期
		, ymdTo : String	//结束日期
		, select : String?	//渠道名
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "report/oldandnewfinancial/index" );
		CommCtrl.send( url
			, param : ["ymdFrom":ymdFrom,"ymdTo":ymdTo,"select":nil==select ? "":select!]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//新老用户理财金额
	static func newOldInvestMoney(
		_ ymdFrom : String	//开始日期
		, ymdTo : String	//结束日期
		, selectedContractId : String?	//渠道名
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "report/oldandnewfinancialamount/index" );
		CommCtrl.send( url
			, param : ["ymdFrom":ymdFrom,"ymdTo":ymdTo,"selectedContractId":nil==selectedContractId ? "":selectedContractId!]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//新老用户理财人均
	static func newOldInvestMoneyPerCapita(
		_ ymdFrom : String	//开始日期
		, ymdTo : String	//结束日期
		, select : String?	//渠道名
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "report/oldandnewfinancialavg/index" );
		CommCtrl.send( url
			, param : ["ymdFrom":ymdFrom,"ymdTo":ymdTo,"select":nil==select ? "":select!]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//资金数据对比
	static func capitalDataCompare(
		_ ymdFrom : String	//开始日期
		, ymdTo : String	//结束日期
		, select : String?	//渠道名
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "report/fundsdata/index" );
		CommCtrl.send( url
			, param : ["ymdFrom":ymdFrom,"ymdTo":ymdTo,"select":nil==select ? "":select!]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//留存数据
	static func remainData(
		_ ymdFrom : String	//开始日期
		, ymdTo : String	//结束日期
		, select : String?	//渠道名
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "report/retaineddata/index" );
		CommCtrl.send( url
			, param : ["ymdFrom":ymdFrom,"ymdTo":ymdTo,"select":nil==select ? "":select!]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//复投人数
	static func investAgainNumbers(
		_ ymdFrom : String	//开始日期
		, ymdTo : String	//结束日期
		, select : String?	//渠道名
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "report/compounddata/index" );
		CommCtrl.send( url
			, param : ["ymdFrom":ymdFrom,"ymdTo":ymdTo,"select":nil==select ? "":select!]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}

	//复投率
	static func investAgainRatio(
		_ ymdFrom : String	//开始日期
		, ymdTo : String	//结束日期
		, select : String?	//渠道名
		, callback :  @escaping ( _ code : Int, _ msg : String?, _ err : CommError? ) -> ()	//callback function
		, view : UIView?	//waiting view's parent
		)
	{
		CommCtrl.start();
		let url : String = CommCtrl.makeUrl( "report/compoundrate/index" );
		CommCtrl.send( url
			, param : ["ymdFrom":ymdFrom,"ymdTo":ymdTo,"select":nil==select ? "":select!]
			, callback : callback
			, type : COMM_TYPE.ui
			, view : nil
			, loading : nil
			, needErr : false
			, exParam : nil
			, userData : nil
			);
	}


}
