<div class="bjui-pageHeader">
    <form  id="pagerForm" method="get" action="<?php echo \Sooh\Base\Tools::uri(); ?>" data-toggle="ajaxsearch">
<!--        <input type="hidden" name="__formguid__" value="default" />-->
<!--        <input type="hidden" name="pageSize" value="--><?php //echo $this->pagesize; ?><!--">-->
<!--        <input type="hidden" name="pageCurrent" value="--><?php //echo $this->pageid; ?><!--">-->
<!--        <input type="hidden" name="orderField" value="${param.orderField}">-->
<!--        <input type="hidden" name="orderDirection" value="${param.orderDirection}">-->
        <label>时间从：</label>
        <input type="text" data-toggle="datepicker" name="ymdFrom" value="<?php echo $this->ymdFrom; ?>" size="18" />
        <label>时间到：</label>
        <input type="text" data-toggle="datepicker" name="ymdTo" value="<?php echo $this->ymdTo; ?>" size="18" />
        
        <label>渠道选择：</label>
        <select name='select' value="channel" id="ids" >
  
         <?php 
          $channel= $this->rem;
          $channels=$this->channels;
//var_log($channel,'66666>>>>>>>');
//var_log($channels,'chanel##########>>>>>>>');

           foreach ($channel as $k=>$v){
               
          ?>
             <option value="<?php echo $v;?>" <?php if($v==$channels) {echo "selected=\"selected\"";}?>><?php echo $v;?></option>
        <?php }?>
        </select>
         <input type="hidden" name="__VIEW__" value="<?php echo $this->_view;?>" size="18" />
       <button type="submit" class="btn btn-default">查询</button>
       &nbsp;
       <label style="color:red;"><?php echo $this->errMsg;?></label>
    </form> 
  </div>
     
<div class="bjui-pageContent">
   
     
   
   <!--<div id="newfinancial" style="height:330px"></div>-->
    
    <div id="newfinancialavgamount" style="height: 430px " width="100%">
     </div>
    
     <div id="newfinancialavgamount1" style="height: 430px " width="100%">
     </div>
    <script type="text/javascript">

        require.config({
            paths:{
                echarts: '/echarts/dist'
        }
        });

        require(
            [
                'echarts',
                'echarts/chart/bar', // 使用柱状图就加载bar模块，按需加载
                'echarts/chart/line', // 使用折线图就加载line模块，按需加载
                //'echarts/chart/stack', // 使用柱状图就加载bar模块，按需加载
                //'echarts/chart/tiled', // 使用柱状图就加载bar模块，按需加载
            ],
            function (ec) {

             
                // 基于准备好的dom，初始化echarts图表
                var myChart = ec.init(document.getElementById('newfinancialavgamount'));

                var records = <?=$this->record?>;
               
                var dtime2 = {text:"<?=$this->dtime2;?>"};
                for(var tx in dtime2){
                   dtime22=dtime2[tx];
                }
//console.log(records);
                var t1='当天注册';
                var t2='前1天至前5天注册';
                var t3='前6天至前30天注册';
                var t4='前31天及更久注册';

                for(var dt in records){
                    tt1=dt+t1; tt2=dt+t2;
                    tt3=dt+t3; tt4=dt+t4;
                   //fbb_avgAmountReg0Day=(parseInt(records[dt][fbb].avgAmountReg0Day);
                    
                   fbb_avgAmountReg0Day=(records[dt].fbb.avgAmountReg0Day);
                   fbb_avgAmountReg1To5=(records[dt].fbb.avgAmountReg1To5);
                   fbb_avgAmountReg6To30=(records[dt].fbb.avgAmountReg6To30);
                   fbb_avgAmountReg31Plus=(records[dt].fbb.avgAmountReg31Plus);

                   dqb_avgAmountReg0Day=(records[dt].dqb.avgAmountReg0Day);
                   dqb_avgAmountReg1To5=(records[dt].dqb.avgAmountReg1To5);
                   dqb_avgAmountReg6To30=(records[dt].dqb.avgAmountReg6To30);
                   dqb_avgAmountReg31Plus=(records[dt].dqb.avgAmountReg31Plus);

                   jyb_avgAmountReg0Day=(records[dt].jyb.avgAmountReg0Day);
                   jyb_avgAmountReg1To5=(records[dt].jyb.avgAmountReg1To5);
                   jyb_avgAmountReg6To30=(records[dt].jyb.avgAmountReg6To30);
                   jyb_avgAmountReg31Plus=(records[dt].jyb.avgAmountReg31Plus);
                   
                  // console.log(dbq_avgAmountReg1To5);
                    }
                
                
                // 指定图表的配置项和数据
                     option = {
              		  title : {
                          subtext: dtime22,//' 2016-08-22--2016-08-23 '
                          text:'新增理财人均（首次投资）'
                      },
                       tooltip : {
                         trigger: 'axis',
                         axisPointer : {            // 坐标轴指示器，坐标轴触发有效
                             type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
                         }
                        },
                         legend: {
                        	 x: 'center',
                             y: 'bottom',
                             data: [t1,t2,t3,t4]//['08-22--08-23-当天注册首次投资','08-22--08-23-前1天至前5天首次投资',
                                  //'08-22--08-23-前6天至前30天首次投资','08-22--08-23-前30天及更久时间首次投资']
                     },
                     xAxis : [
                         {
                             type : 'category',
                             data : ['定期宝','房宝宝','精英宝']   // ['周一','周二','周三','周四','周五','周六','周日']
                         }
                     ],
                     yAxis : [
                         {
                             type : 'value',
                             axisLabel:{
                                 formatter: function(value, inddx) {
                                     return value / 1000 + '千';
                                 }
                             }
                         }
                     ],
                     grid: {
                         x: '10%',
                         x2: '15',
                         y2: '80',
                         containLabel: true
                     },
                     series : [
                         {
                             name:t1,//'08-22--08-23-当天注册首次投资',
                             type:'bar',
                            // stack: '广告',
                             data:[dqb_avgAmountReg0Day, fbb_avgAmountReg0Day, jyb_avgAmountReg0Day]
                         },
                         {
                             name:t2,//'08-22--08-23-前1天至前5天首次投资',
                             type:'bar',
                             //stack: '广告',
                             data:[dqb_avgAmountReg1To5, fbb_avgAmountReg1To5, jyb_avgAmountReg1To5]
                         },
                         {
                             name:t3,//'08-22--08-23-前6天至前30天首次投资',
                             type:'bar',
                             //stack: '广告',
                             data:[dqb_avgAmountReg6To30, fbb_avgAmountReg6To30, jyb_avgAmountReg6To30]
                         },
                         {
                            name:t4,//'08-22--08-23-前30天及更久时间首次投资',
                             type:'bar',
                            // stack: '广告',
                             data:[dqb_avgAmountReg31Plus, fbb_avgAmountReg31Plus, jyb_avgAmountReg31Plus]
                         },
                        
                     ]
                 };

                // 为echarts对象加载数据
                myChart.setOption(option);
                // 基于准备好的dom，初始化echarts图表
                var mynewChart = ec.init(document.getElementById('newfinancialavgamount1'));

                var records1 = <?=$this->record1?>;
               
                var dtime3 = {text:"<?=$this->dtime3;?>"};
                for(var tx1 in dtime3){
                    dtime33=dtime3[tx1];
                }

                for(var dt1 in records1){
                    tt11=dt1+t1; tt22=dt1+t2;
                    tt33=dt1+t3; tt44=dt1+t4;
                   //fbb_avgAmountReg0Day=(parseInt(records[dt][fbb].avgAmountReg0Day);
                    
                   fbb1_avgAmountReg0Day=(records1[dt1].fbb.avgAmountReg0Day);
                   fbb1_avgAmountReg1To5=(records1[dt1].fbb.avgAmountReg1To5);
                   fbb1_avgAmountReg6To30=(records1[dt1].fbb.avgAmountReg6To30);
                   fbb1_avgAmountReg31Plus=(records1[dt1].fbb.avgAmountReg31Plus);

                   dqb1_avgAmountReg0Day=(records1[dt1].dqb.avgAmountReg0Day);
                   dqb1_avgAmountReg1To5=(records1[dt1].dqb.avgAmountReg1To5);
                   dqb1_avgAmountReg6To30=(records1[dt1].dqb.avgAmountReg6To30);
                   dqb1_avgAmountReg31Plus=(records1[dt1].dqb.avgAmountReg31Plus);

                   jyb1_avgAmountReg0Day=(records1[dt1].jyb.avgAmountReg0Day);
                   jyb1_avgAmountReg1To5=(records1[dt1].jyb.avgAmountReg1To5);
                   jyb1_avgAmountReg6To30=(records1[dt1].jyb.avgAmountReg6To30);
                   jyb1_avgAmountReg31Plus=(records1[dt1].jyb.avgAmountReg31Plus);
                   
                  // console.log(dbq_avgAmountReg1To5);
                    }
                
                // 指定图表的配置项和数据
                  option = {
              		  title : {
                          subtext: dtime33,//' 2016-08-23--2016-08-24 '
                          text:'新增理财人均（首次投资）'
                      },
                       tooltip : {
                         trigger: 'axis',
                         axisPointer : {            // 坐标轴指示器，坐标轴触发有效
                             type : 'shadow'        // 默认为直线，可选为：'line' | 'shadow'
                         }
                        },
                     legend: {
                    	 x: 'center',
                         y: 'bottom',
                         data:[t1,t2,t3,t4]
                             //  ['08-23--08-24-当天注册首次投资','08-23--08-24-前1天至前5天首次投资',
                             //  '08-23--08-24-前6天至前30天首次投资','08-23--08-24-前30天及更久时间首次投资']
                        
                     },
                     xAxis : [
                         {
                             type : 'category',
                             data : ['定期宝','房宝宝','精英宝']   // ['周一','周二','周三','周四','周五','周六','周日']
                         }
                     ],
                     yAxis : [
                         {
                             type : 'value',
                             axisLabel:{
                                 formatter: function(value, inddx) {
                                     return value / 1000 + '千';
                                 }
                             }
                         }
                     ],
                     grid: {
                          x: '10%',
                          x2: '15',
                          y2: '80',
                          containLabel: true
                     },
                     series : [
                         {
                             name:t1,//'08-23--08-24-当天注册首次投资',
                             type:'bar',
                            // stack: '搜索引擎',
                             data:[dqb1_avgAmountReg0Day, fbb1_avgAmountReg0Day, jyb1_avgAmountReg0Day]
                         },
                         {
                             name:t2,//'08-23--08-24-前1天至前5天首次投资',
                             type:'bar',
                             //stack: '搜索引擎',
                             data:[dqb1_avgAmountReg1To5,fbb1_avgAmountReg1To5, jyb1_avgAmountReg1To5]
                         },
                         {
                             name:t3,//'08-23--08-24-前6天至前30天首次投资',
                             type:'bar',
                            // stack: '搜索引擎',
                             data:[dqb1_avgAmountReg6To30, fbb1_avgAmountReg6To30, jyb1_avgAmountReg6To30]
                         },
                          {
                             name:t4,//'08-23--08-24-前30天及更久时间首次投资',
                             type:'bar',
                            // stack: '搜索引擎',
                             data:[dqb1_avgAmountReg31Plus, fbb1_avgAmountReg31Plus, jyb1_avgAmountReg31Plus]
                         },
                        
                     ]
                 };
                        // 为echarts对象加载数据
                  mynewChart.setOption(option);
            }
        );
    </script>
</div>


