<form action="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1), 'dailybid'); ?>" method="post" id="contracts-exportChecked" style="display: none;">
</form>
<div class="bjui-pageHeader">

    <form  id="pagerForm" class="classOfForm" method="get" action="<?php echo \Sooh\Base\Tools::uri(); ?>" data-toggle="ajaxsearch">
        <input type="hidden" name="__formguid__" value="default" />
        <input type="hidden" name="pageSize" value="<?php echo $this->pagesize; ?>">
        <input type="hidden" name="pageCurrent" value="<?php echo $this->pageid; ?>">
        <input type="hidden" name="orderField" value="${param.orderField}">
        <input type="hidden" name="orderDirection" value="${param.orderDirection}">
        <label>发放起始日期：</label>
        <input type="text" data-toggle="datepicker" name="ymdFrom" value="<?php echo $this->ymdFrom; ?>" size="18" />
        &nbsp;
        <label>截止日期：</label>
        <input type="text" data-toggle="datepicker" name="ymdTo" value="<?php echo $this->ymdTo; ?>" size="18" />
<!--        &nbsp;-->
<!--        <label>用户ID：</label>-->
<!--        <input type="text"  name="userId" value="--><?php //echo $this->userId; ?><!--" size="18" />-->
        &nbsp;
        <label>手机号：</label>
        <input type="text"  name="phone" data-rule="digits" value="<?php echo $this->phone; ?>" size="18" />
        &nbsp;
        <label>姓名：</label>
        <input type="text"  name="realname" value="<?php echo $this->realname; ?>" size="18" />
<!--        &nbsp;-->
<!--        <label>标的ID：</label>-->
<!--        <input type="text"  name="waresId" value="--><?php //echo $this->waresId; ?><!--" size="18" />-->
        &nbsp;
        <label>优惠券类型：</label>
        <select name="voucherType" >
            <?php
                $arrVoucherType = $this->arrVoucherType;
                $selectedVoucherType =$this->selectedVoucherType;
                foreach($arrVoucherType as $type => $name) {
            ?>
                    <option value="<?php echo $type;?>" <?php echo ($type==$selectedVoucherType) ? 'selected=\"selected\"':'' ;?>><?php echo $name;?></option>
            <?php
                }
            ?>
        </select>
        &nbsp
        <button type="submit" class="btn btn-default">查询</button>
        <a class="btn btn-orange" href="javascript:;" data-toggle="reloadsearch" data-clear-query="true" data-icon="undo">清空查询</a>
        <br />
        <label>
            <span style="line-height: 24px;"><?php echo $this->summary;?></span>
        </label>
    </form>
    <script>
        var hide = <?=$this->hide+0;?>;
        if(hide==1){
            console.log('hide:'+hide);
//            var objForm = document.getElementsByClassName('classOfForm');
//            objForm.style.display='none';
            $('.classOfForm').hide();
        }
    </script>

    <div class="pull-right">
        <div class="btn-group">
            <button type="button" class="btn-default dropdown-toggle" data-toggle="dropdown" data-icon="copy">复选框-批量操作<span class="caret"></span></button>
            <ul class="dropdown-menu right" role="menu">
                <li><a href="<?php echo \Sooh\Base\Tools::uri(array('__EXCEL__'=>1,'where'=>$this->where),'detail'); ?>">导出<span style="color: green;">全部</span></a></li>
                <!--                    <li><a class="contracts-export" style="cursor: pointer">导出<span style="color: red">选中</span></a></li>-->
                <li class="divider"></li>
            </ul>
        </div>

        <script>
            /** 构造表单 post 方法 提交 */
            var ids = new Array();
            $('.contracts-export').click(function(){
                if(ids.length==0)
                {
                    $(document).alertmsg('error', '无选中选项');
                    return false;
                }
                $('#contracts-exportChecked').html(''); //add ' '
                for(var i in ids)
                {
                    var reg = /function[.]*/;
                    if(reg.exec(ids[i])!=null)
                    {
                        continue;
                    }
                    $('#contracts-exportChecked').append("<input type='hidden' name='ids[]' value='"+ids[i]+"'>");
                }
                $('#contracts-exportChecked').submit();
                return false;
            });
        </script>
    </div>
</div>

<div class="bjui-pageContent tableContent">
    <table class="table table-bordered table-hover table-striped table-top" data-selected-multi="true" data-toggle="tablefixed">
        <thead>

        <tr>
            <?php
            if(!empty($this->fieldsMap)) {
                foreach($this->fieldsMap as $title => $width) {
                    ?>
                    <th width = '<?php  echo $width;?>'><?php echo $title; ?></th>
                    <?php
                }
            }

            ?>

        </tr>
        </thead>
        <tbody>
        <?php
        if(!empty($this->records)) {
            foreach($this->records as $r) {
                $pkey = $r['__PKEY__'];
                unset ($r['__PKEY__']);
                echo "<tr data-id=\"".$pkey."\"><td>";
                echo implode('</td><td>', $r);
                echo "</td>";
                echo "</tr>";
            }
        }
        ?>
        </tbody>
    </table>
</div>

<div class="bjui-pageFooter">
    <ul>
        <li><button type="button" class="btn-close" data-icon="close">关闭</button></li>
    </ul>
    <div class="pages">
        <span>每页&nbsp;</span>
        <div class="selectPagesize">
            <select data-toggle="selectpicker" data-toggle-change="changepagesize">
                <?php
                $pager = $this->pager;
                $r = explode(',', $pager->enumPagesize);
                foreach($r as $v){
                    $str .= "<option value=\"$v\">$v</option>";
                }
                echo $str;
                ?>
            </select>
        </div>
        <span>&nbsp;条，共 <?php echo $pager->total; ?> 条,&nbsp;&nbsp;共<?php echo $pager->page_count;?>页</span>
    </div>
    <div class="pagination-box" data-toggle="pagination" data-total="<?php echo $pager->total; ?>" data-page-size="<?php echo $pager->page_size; ?>" data-page-current="<?php $pager->pageid(); ?>"></div>

</div>
































