<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#" onclick="top.location.href='/manage/manager/index?__VIEW__=html'">转PC端</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
			<?php
			$menulist = $this->wapMenuList;
			$curMenu = $menulist['__'];
			unset($menulist['__']);
			foreach($menulist as $capt=>$url){
				echo "\n<li ".($capt==$curMenu?'class="active"':'')."><a href=\"$url\">$capt</a></li>";
			}
			?>
          </ul>
		<!--
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
          </ul>
		  -->
        </div><!--/.nav-collapse -->
      </div>
    </nav>